(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h0=function(a){a.W("cardstatechange",a.Sh()&&a.Pl()?1:0)},i0=function(a,b){var c=g.Ia(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},PVa=function(a){var b=g.Jk(a);
a=g.Mk(a);return new g.vk(b.x,b.y,a.width,a.height)},QVa=function(a){return Math.pow(a,3)},RVa=function(a){return 3*a*a-2*a*a*a},l0=function(a){a=g.Ma(a);
delete j0[a];g.xe(j0)&&k0&&k0.stop()},TVa=function(){k0||(k0=new g.K(function(){SVa()},20));
var a=k0;a.isActive()||a.start()},SVa=function(){var a=g.Qa();
g.ke(j0,function(b){UVa(b,a)});
g.xe(j0)||TVa()},m0=function(a,b,c,d){g.Dn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.P=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},UVa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;VVa(a,a.progress);1==a.progress?(a.j=0,l0(a),a.onFinish(),a.Ty()):a.isPlaying()&&a.JE()},VVa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.P[c]-a.u[c])*b+a.u[c]},WVa=function(a,b){g.ee.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},n0=function(a,b,c,d,e){m0.call(this,b,c,d,e);
this.element=a},o0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
n0.call(this,a,b,c,d,e)},p0=function(a){g.I.call(this);
this.u=a||window;this.j=[]},q0=function(a){return a.baseUrl||null},r0=function(a,b){return g.zl(g.Oj(a,b),function(c){return!!c})},XVa=function(a,b,c){function d(X){var oa=X.hovercardButton;
if(!oa)return null;oa=oa.subscribeButtonRenderer;if(!oa)return null;var Ja=f(oa.unsubscribedButtonText),Sa=f(oa.subscribedButtonText);if(oa.subscribed){var Za=f(oa.subscriberCountWithUnsubscribeText);var eb=f(oa.subscriberCountText)}else Za=f(oa.subscriberCountText),eb=f(oa.subscriberCountWithSubscribeText);var Vb=null;if(X.signinEndpoint){Vb=i0(X,"signinEndpoint","webNavigationEndpointData","url");if(!Vb){var Wb,fc,Na;Vb=null==(Wb=oa.signInEndpoint)?void 0:null==(fc=Wb.commandMetadata)?void 0:null==
(Na=fc.webCommandMetadata)?void 0:Na.url}if(!Vb)return null}return Ja&&(Sa||Vb)?{subscribed:oa.subscribed,subscribeText:Ja,subscribeCount:Za,unsubscribeText:Sa,unsubscribeCount:eb,enabled:oa.enabled,signinUrl:Vb,classic:X.useClassicSubscribeButton}:null}
function e(X){if(X){var oa=[],Ja=X.videoId;Ja&&oa.push("v="+Ja);(Ja=X.playlistId)&&oa.push("list="+Ja);(X=X.startTimeSeconds)&&oa.push("t="+X);return"/watch?"+oa.join("&")}}
function f(X){if(!X)return null;var oa=X.simpleText;return oa?oa:X.runs?g.Oj(X.runs,function(Ja){return Ja.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,u=null,x=null,y=!1,z=null,D=null,G=null,H=null,L=null,aa=null;if("VIDEO"===k)l.urlEndpoint?m=l.urlEndpoint.url:(aa=l.watchEndpoint,m=e(aa)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===k)l.urlEndpoint?m=l.urlEndpoint.url:(aa=l.watchEndpoint,m=e(aa)),n=!1,q=a,u=f(b.playlistLength);
else if("CHANNEL"===k){if(y=i0(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;q="new";(y=!!b.isSubscribe)?z=d(b):D=f(b.subscribersText)}else"WEBSITE"===k?((G=i0(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===k&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=i0(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=i0(b,"title","accessibility","accessibilityData","label");var M=b.endpoint?b.endpoint.clickTrackingParams:
null,ha="";if(b.metadata){var ra=f(b.metadata);ra&&(ha=ra)}return{id:"element-"+c,type:k,title:f(b.title),metadata:ha,callToAction:f(b.callToAction),kN:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:u,channelId:x,subscribeButton:z,subscribersText:D,isSubscribe:y,targetUrl:m||null,bX:n,sessionData:M?{itct:M}:null,L0:q,
Xw:a?a:null,isPlaceholder:b.isPlaceholder,impressionUrls:r0(b.impressionUrls||[],q0),QW:r0(b.hovercardShowUrls||[],q0),clickUrls:r0(l.loggingUrls||[],q0),visualElement:g.ku(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:aa||null}},s0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:r0(a.impressionUrls||[],q0),elements:r0(a.elements||[],function(d,e){return XVa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.ku(a.trackingParams));return c},t0=function(a){g.EI.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.P=!0;this.I=0;a=a.R();this.isEmbedded=g.KA(a)||g.OA(a);this.U=a.experiments.bb("web_rounded_thumbnails");this.events=new g.Ry(this);g.J(this,this.events);this.events.N(this.player,g.iv("creatorendscreen"),this.onCueRangeEnter);this.events.N(this.player,g.jv("creatorendscreen"),this.onCueRangeExit);this.events.N(this.player,"resize",this.ub);this.events.N(window,"focus",this.H_);this.load();var b=g.dg("STYLE");(g.Wf("HEAD")[0]||
document.body).appendChild(b);g.de(this,function(){g.hg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},YVa=function(a){return a.player.getVideoData().D?"current":a.isEmbedded?"new":"current"},u0=function(a){return"creator-endscreen-editor"===a.player.R().playerStyle},ZVa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=s0(f,YVa(a))));v0(a,f)},
urlParams:{v:c},withCredentials:!0};a.isEmbedded&&(c.urlParams.ptype="embedded");var d=b.Kr;d&&(c.postParams={ad_tracking:d});if(b=g.pya(b))if(b=g.kf(b),b=g.hf(b))a.B=g.Tp(b,c)},v0=function(a,b,c){c=void 0===c?!0:c;
a.player.yf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&$Va(a);c=[];d=new g.gv(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.R().isMobile||(a.u=new g.V({F:"div",L:"ytp-ce-shadow"}),g.oI(a.player,a.u.element,4),a.C=new g.MG(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=aWa(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.oI(a.player,f.element,4);var k=new g.gv(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);bWa(a,
f,e)}else g.hu(new g.dr("buildEndscreenElement null",e))}a.player.Sd(c);a.ub()}},$Va=function(a){var b=g.qu(),c=g.ru();
c&&b&&a.endscreen.visualElement&&g.wu(void 0,c,b,[a.endscreen.visualElement])},aWa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ba:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.Xw||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:w0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:x0(a,b.targetUrl),tabindex:"-1"},S:[{F:"div",Ba:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.Hn(b.title||"")},X:b.title},{F:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
X:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={F:"div",Ba:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.Xw||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:w0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:x0(a,b.targetUrl),tabindex:"-1"},S:[{F:"div",Ba:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.Hn(b.title||"")},X:b.title},{F:"div",L:"ytp-ce-playlist-count",
S:[{F:"div",L:"ytp-ce-playlist-icon"},{F:"div",L:"ytp-ce-playlist-count-text",X:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={F:"div",Ba:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.Xw||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",S:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
S:[{F:"div",L:"ytp-ce-expanding-overlay-body",S:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{F:"a",Ba:["ytp-ce-channel-title","ytp-ce-link"],T:{href:x0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Hn(b.title||"")},X:b.title},b.subscribeButton?{F:"div",L:"ytp-ce-subscribe-container",S:[{F:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",L:"ytp-ce-channel-subscribers-text",X:b.subscribersText}:"",b.metadata?{F:"div",Ba:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],X:b.metadata}:""]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:w0(b)}]};c=new g.V(c);var d=g.Xf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.sn(d,"ytp-ce-subscribe-button");if(a.player.R().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.JJ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ba:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.Xw||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",S:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
S:[{F:"div",L:"ytp-ce-expanding-overlay-body",S:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{F:"div",L:"ytp-ce-website-title",T:{dir:g.Hn(b.title||"")},X:b.title},{F:"div",L:"ytp-ce-website-metadata",X:b.metadata},{F:"a",Ba:["ytp-ce-website-goto","ytp-ce-link"],T:{href:x0(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:w0(b)},{F:"div",L:"ytp-ce-expanding-icon",T:cWa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",L:"ytp-ce-merchandise-price-container",S:[{F:"div",L:"ytp-ce-merchandise-price",X:b.productPrice}]},b.additionalFeesText&&c.S.push({F:"div",L:"ytp-ce-merchandise-additional-fees",X:b.additionalFeesText})),a={F:"div",Ba:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.Xw||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",S:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},
{F:"div",L:"ytp-ce-expanding-overlay-content",S:[{F:"div",L:"ytp-ce-expanding-overlay-body",S:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{F:"div",L:"ytp-ce-merchandise-title",T:{dir:g.Hn(b.title||"")},X:b.title},c,{F:"div",L:"ytp-ce-merchandise-metadata",X:b.metadata},{F:"a",Ba:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:x0(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:w0(b)},{F:"div",L:"ytp-ce-merchandise-invideo-cta-container",
S:[{F:"div",L:"ytp-ce-merchandise-invideo-cta",X:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.sn(c.element,"ytp-ce-placeholder");return c},w0=function(a){if(a.kN)var b=a.kN.thumbnails;
return cWa(b?b[b.length-1].url:null)},cWa=function(a){return a?{style:"background-image: url("+a+")"}:{}},bWa=function(a,b,c){function d(m){m&&(b.Ja("blur",function(){"none"!=m.style.display&&a.P&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",k))}
function e(m){a.I+=m;0<a.I?(g.sn(b.element,"ytp-ce-force-expand"),y0(a,c.id,!0)):(g.un(b.element,"ytp-ce-force-expand"),g.un(b.element,"ytp-ce-element-hover"),y0(a,c.id,!1))}
function f(){e(1)}
function k(){e(-1)}
b.Ja("mouseenter",function(){z0(a,b,c)});
b.Ja("mouseleave",function(){A0(a,b,c)});
a.player.R().isMobile||b.Ja("click",function(){g.sn(b.element,"ytp-ce-element-hover")});
b.Ja("click",function(m){dWa(a,c,m)});
b.Ja("keypress",function(m){dWa(a,c,m)});
b.Ja("focus",function(){z0(a,b,c)});
b.Ja("blur",function(){A0(a,b,c)});
b.Ja("touchstart",function(){z0(a,b,c)});
var l=g.Zf("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.un(b.element,"ytp-ce-element-hover");g.un(b.element,"ytp-ce-force-expand")});
b.Ja("keydown",function(m){a.P=9===m.keyCode&&!m.shiftKey});
d(g.Zf("ytp-sb-subscribe",b.element));d(g.Zf("ytp-sb-unsubscribe",b.element));b.Ja("focus",f);b.Ja("blur",k)},dWa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.rn(d,"ytp-ce-element");){g.rn(d,"subscribe-label")&&B0(a,b);
if(g.rn(d,"ytp-ce-channel-subscribe"))return;d=g.ig(d)}if(!d||g.rn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])A0(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.L0)B0(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.kf(x0(a,b.targetUrl)),g.lH(g.hf(c),void 0,b.sessionData);else{var e=g.cB(a.player.R())||a.player.getVideoData().D,f=function(){var k=x0(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.Fp(k);e&&n&&(n.v||n.list)?
a.player.ll(n.v,l,n.list,!1,void 0,m||void 0):g.kH(k,l)};
B0(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},x0=function(a,b){a=a.player.R();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.mB(a)+b}else return"";return b},z0=function(a,b,c){g.rn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.sn(b.element,"ytp-ce-element-hover"):a.player.R().isMobile?(new g.K(function(){g.sn(b.element,"ytp-ce-element-hover")},200)).start():g.sn(b.element,"ytp-ce-element-hover"),C0(a,c.QW),y0(a,c.id,!0))},A0=function(a,b,c){g.un(b.element,"ytp-ce-element-hover");
g.un(b.element,"ytp-ce-force-expand");y0(a,c.id,!1)},y0=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.j[e].element,"ytp-ce-element-shadow-show",c)},C0=function(a,b,c){function d(){f||(e++,e===b.length&&(k.stop(),c&&c()))}
if(!b||0===b.length||u0(a))c&&c();else{b=eWa(a,b);var e=0,f=!1,k=new g.K(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.ls(b[a],d)}},B0=function(a,b,c){C0(a,b.clickUrls,c);
(a=g.ru())&&b.bX&&g.Cu(a,b.visualElement)},eWa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(fWa(b[d],c));return a},fWa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},gWa=function(a){return"string"===typeof a?a:""},D0=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},hWa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},E0=function(a){return a.value?a.value:null},F0=function(a){if(!a)return null;
var b=g.kf(gWa(a.value));b=g.hf(b);if(!b)return null;var c=D0(a.target,iWa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new hWa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},jWa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},mWa=function(a){if(!a)return null;
var b=D0(a.type,kWa),c=D0(a.trigger,lWa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=F0(a?a:null);return b?new jWa(b,c,a):null},nWa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},pWa=function(a){return(a=oWa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},oWa=function(a,b){return g.Db(a.action,b)},qWa=function(a,b){this.context=a;
this.j=b},H0=function(a){return a.customMessage?G0("div","iv-card-message",a.customMessage):""},I0=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",L:"iv-card-image",T:{style:a},S:c}},J0=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(G0("li","",c.value));return{F:"ul",L:"iv-card-meta-info",S:b}},G0=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Hn(c);return{F:a,T:b,X:c}},rWa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.jx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.jx+");");c.dir=g.Hn(a.customMessage);var d=[{F:"span",X:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",L:"iv-card-link-icon"}));return{F:"div",Ba:b,T:c,S:d}},K0=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},sWa=function(a,b){this.merchant=a;
this.price=b},tWa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},uWa=function(a,b){return b?b:tWa(a)?"current":"new"},L0=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.ib=!1;this.Qa=new Map;this.Sa=new Map;this.context.G.addEventListener(g.iv("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.jv("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)})},M0=function(a,b,c,d,e,f,k){a.context.j.Ja(b,"click",function(l){a.KE(c,d,e,f||[],k||0,l)});
a.context.j.Ja(b,"touchstart",function(){a.ib=!1});
a.context.j.Ja(b,"touchmove",function(){a.ib=!0})},vWa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},N0=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
AR:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
xD:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Q0=function(a,b,c){L0.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ka=this.Kb=this.B=this.isInitialized=!1;this.ma=null;this.cards=[];this.sb=this.P=this.Ga=this.D=this.Pa=this.j=null;this.V=[];this.Z=this.J=this.Ze=this.Ca=null;this.I=0;this.ya=new g.K(function(){},c.environmentData.Ue?4E3:3E3);
g.J(this,this.ya);this.Za=new g.K(function(){});
g.J(this,this.Za);this.ea=new qWa(c,function(e,f,k,l,m,n){M0(d,e,f,k,l,m,n)});
this.U=new g.V({F:"div",L:"iv-drawer",T:{id:"iv-drawer"},S:[{F:"div",L:"iv-drawer-header",T:{"aria-role":"heading"},S:[{F:"span",L:"iv-drawer-header-text"},{F:"button",Ba:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",L:"iv-drawer-content"}]});g.J(this,this.U);this.C=this.U.element;this.Ya=new g.MG(this.U,330);g.J(this,this.Ya);this.Gb=g.Zf("iv-drawer-header-text",this.C);this.u=g.Zf("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Kb&&O0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.B)&&P0(d)});
this.G.addEventListener("videodatachange",this.yp.bind(this))},wWa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){O0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){P0(a)});
var c=b.headerText;g.kg(a.Gb,c);a.P&&a.P.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ca=g.ku(b.trackingParams);a.J=g.ku(b.closeTrackingParams);a.Ze=g.ku(b.iconTrackingParams)},xWa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.R().experiments.bb("enable_error_corrections_infocard");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){d=b.teaser.simpleCardTeaserRenderer;var e=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.nv(d.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},Ql:null,mj:d.trackingParams?g.ku(d.trackingParams):null,Ze:e&&e.trackingParams?g.ku(e.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,jx:null,title:"",customMessage:"",url:null,onClickCommand:d.onTapCommand||null};R0(a,b)}else if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.nv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:S0(a,
c,b,d),sponsored:!1,tracking:N0(d,e,d.command),Ql:d.trackingParams?g.ku(d.trackingParams):null,mj:e.trackingParams?g.ku(e.trackingParams):null,Ze:f&&f.trackingParams?g.ku(f.trackingParams):null,imageUrl:T0(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.nv(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,jx:null,title:d.title?g.nv(d.title):"",customMessage:d.callToAction?g.nv(d.callToAction):"",url:d.command.urlEndpoint.url?F0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.command.urlEndpoint.url}):null,onClickCommand:null};R0(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.nv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:S0(a,
c,b,d),sponsored:!1,tracking:N0(d,e,d.endpoint),Ql:d.trackingParams?g.ku(d.trackingParams):null,mj:e.trackingParams?g.ku(e.trackingParams):null,Ze:f&&f.trackingParams?g.ku(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.nv(d.customText):null,profileImageUrl:T0(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.nv(d.channelName):"",metaInfo:[d.subscriberCountText?g.nv(d.subscriberCountText):""],url:F0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId}),onClickCommand:null};R0(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.nv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:S0(a,c,b,d),sponsored:!1,tracking:N0(d,e,d.action),Ql:d.trackingParams?g.ku(d.trackingParams):null,mj:e.trackingParams?g.ku(e.trackingParams):null,Ze:f&&f.trackingParams?g.ku(f.trackingParams):null,thumbnailImageUrl:T0(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.nv(d.customMessage):null,playlistVideoCount:g.nv(d.playlistVideoCount),title:d.playlistTitle?g.nv(d.playlistTitle):"",metaInfo:[d.channelName?
g.nv(d.channelName):"",d.videoCountText?g.nv(d.videoCountText):""],url:F0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:vWa(d.action)}),onClickCommand:null};R0(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.nv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:S0(a,c,b,d),sponsored:!1,tracking:N0(d,e,d.action),Ql:d.trackingParams?g.ku(d.trackingParams):null,mj:e.trackingParams?g.ku(e.trackingParams):null,Ze:f&&f.trackingParams?g.ku(f.trackingParams):null,thumbnailImageUrl:T0(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.nv(d.lengthString):null,customMessage:d.customMessage?g.nv(d.customMessage):null,title:d.videoTitle?g.nv(d.videoTitle):"",metaInfo:[d.channelName?
g.nv(d.channelName):"",d.viewCountText?g.nv(d.viewCountText):""],isLiveNow:!!d.badge,url:F0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:vWa(d.action)}),onClickCommand:null};R0(a,b)}a.I++},T0=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},S0=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},zWa=function(a,b){if(b=yWa(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.hg(b.BF),g.Ib(a.cards,b),a.JA(),U0(a)},O0=function(a,b,c){if(!a.B){a.Ya.show();
a.Pa=new g.K(function(){g.sn(a.context.G.getRootNode(),g.kO.IV_DRAWER_OPEN)},0);
a.Pa.start();a.ma=g.Os(a.u,"mousewheel",function(k){a.ya.start();k.preventDefault();k=k||window.event;var l=0;"MozMousePixelScroll"==k.type?l=0==(k.axis==k.HORIZONTAL_AXIS)?k.detail:0:window.opera?l=k.detail:l=0==k.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?k.wheelDeltaY/-30:k.wheelDeltaY/-1.2:k.wheelDelta/-1.6:k.wheelDeltaY/-3;if(k=l)a.u.scrollTop+=k});
a.B=!0;var d=g.ru();d&&a.Ca&&a.J&&g.Au(d,[a.Ca,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.WO||(f.WO=!0,AWa(a.context.logger,f.card.tracking.impression,b)),d&&g.Au(d,[f.card.Ql]);h0(a.G);c&&(a.D=new g.K(function(){a.Ga=a.P;a.sb.focus()},330),a.D.start())}},P0=function(a){a.B&&(a.Ya.hide(),g.Ps(a.ma),a.ma=null,g.un(a.context.G.getRootNode(),g.kO.IV_DRAWER_OPEN),a.B=!1,h0(a.G),a.D&&a.D.stop(),a.D=new g.K(function(){a.Ga&&(a.Ga.focus(),a.Ga=null)},330),a.D.start())},
CWa=function(a){g.tn(a.element,[g.kO.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.oI(a.G,a.C,5);BWa(a);a.P=g.Zf("ytp-cards-button",a.G.getRootNode());a.sb=g.Zf("iv-drawer-close-button",a.C);a.isInitialized=!0},BWa=function(a){var b=g.Zf("iv-drawer-close-button",a.C);
a.context.j.Ja(b,"click",a.zV,a);a.context.j.Ja(a.u,"touchend",function(){a.ya.start()});
a.context.j.Ja(a.u,"scroll",a.MV,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.rn(a.G.getRootNode(),"ytp-autohide")});
a.V.push(g.gt("iv-button-shown",a.kX,a));a.V.push(g.gt("iv-button-hidden",a.jX,a));a.V.push(g.gt("iv-teaser-shown",a.xU,a));a.V.push(g.gt("iv-teaser-hidden",a.lX,a));a.V.push(g.gt("iv-teaser-clicked",a.wU,a))},DWa=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,k=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===k.key&&(f=void 0,(k=null==(f=k.value)?void 0:f.markers)&&0<k.length))return d=void 0,b.startMs=(null==(d=k[0].markerRenderer)?void 0:d.timeRangeStartMillis)||0,a.Z=null,!0}}a.Z=b;return!1},R0=function(a,b){if(b.onClickCommand&&b.onClickCommand.changeEngagementPanelVisibilityAction&&"engagement-panel-error-corrections"===b.onClickCommand.changeEngagementPanelVisibilityAction.targetId){a.Z=
b;
var c=!0}else c=!1;if(!c||DWa(a,b))if(c=EWa(a,b)){var d={card:b,BF:c.element,WO:!1};if(!b.onClickCommand){a.isInitialized||CWa(a);zWa(a,b.id);var e=FWa(a,d);g.Ob(a.cards,e,0,d);c.ra(a.u,e);a.JA()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,U0(a),GWa(a,d),O0(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&HWa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){HWa(a,d)}),U0(a))}},EWa=function(a,b){switch(b.type){case "simple":a=
a.ea;
var c=b.displayDomain?{F:"div",L:"iv-card-image-text",X:b.displayDomain}:void 0;var d=rWa(b);c={F:"div",Ba:["iv-card"],S:[{F:"a",L:"iv-click-target",T:{href:b.url?E0(b.url)||"":""},S:[I0(b.imageUrl,c),{F:"div",L:"iv-card-content",S:[G0("h2",void 0,b.title),d]}]}]};c=new g.V(c);K0(a,g.Yf("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ea,c={F:"div",Ba:["iv-card","iv-card-channel"],S:[{F:"a",Ba:["iv-click-target"],T:{href:E0(b.url)||"","data-ytid":b.channelId},S:[I0(b.profileImageUrl),
{F:"div",L:"iv-card-content",S:[H0(b),{F:"h2",L:"iv-card-primary-link",X:b.title},J0(b)]}]}]},c=new g.V(c),K0(a,g.Yf("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ea,c={F:"div",Ba:["iv-card","iv-card-playlist"],S:[{F:"a",L:"iv-click-target",T:{href:E0(b.url)||""},S:[I0(b.thumbnailImageUrl,{F:"div",L:"iv-card-image-overlay",S:[{F:"span",L:"iv-card-playlist-video-count",X:b.playlistVideoCount}]}),{F:"div",L:"iv-card-content",S:[H0(b),G0("h2","iv-card-primary-link",b.title),J0(b)]}]}]},
c=new g.V(c),K0(a,g.Yf("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ea;var e=!g.Gb(b.offers);c=["iv-card"];d="";var f=rWa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({F:"div",L:"iv-card-offer-price",X:f.price}),f.merchant&&e.push({F:"div",L:"iv-card-offer-merchant",X:f.merchant}),f={F:"div",S:e});e=b.url?E0(b.url)||"":"";c={F:"div",Ba:c,T:{tabindex:"0"},S:[{F:"a",Ba:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{F:"div",L:"iv-card-content",S:[b.sponsored?{F:"div",L:"iv-card-sponsored",S:["Sponsored",{F:"div",L:"iv-ad-info-container",S:[{F:"div",L:"iv-ad-info",X:"{{adInfo}}"},{F:"div",L:"iv-ad-info-icon-container",S:[{F:"div",L:"iv-ad-info-icon"},{F:"div",L:"iv-ad-info-callout"}]}]}]}:"",{F:"a",L:"iv-click-target",T:{href:e},S:[G0("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.dg("span");g.kg(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Gd(d,"adInfo");K0(a,g.Yf("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ea,d=b.videoDuration?{F:"span",L:"iv-card-video-duration",X:b.videoDuration}:void 0,f=b.isLiveNow?{F:"span",Ba:["yt-badge","yt-badge-live"],X:"LIVE NOW"}:null,e={F:"div",Ba:["iv-card","iv-card-video"],S:[{F:"a",L:"iv-click-target",T:{href:(null==(c=b.url)?void 0:E0(c))||""},S:[I0(b.thumbnailImageUrl,d),{F:"div",L:"iv-card-content",S:[H0(b),G0("h2","iv-card-primary-link",b.title),J0(b),f]}]}]},c=new g.V(e),
K0(a,g.Yf("iv-click-target",c.element),b,b.url),c;default:return null}},FWa=function(a,b){if(0===a.cards.length)return 0;
a=g.Eb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},IWa=function(a){return a.j?"productListing"===a.j.card.type:g.Pj(a.cards,function(b){return"productListing"===b.card.type})},U0=function(a){g.N(a.G.getRootNode(),"ytp-cards-shopping-active",IWa(a))},HWa=function(a,b){if(!g.rn(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.ru(),d=a.j?a.j.card.Ze:a.Ze;
c&&d&&g.Bu(c,[d]);a.j=b;U0(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Iv(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.Za.isActive()||((!a.B||!a.ya.isActive()&&a.Ka)&&GWa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},GWa=function(a,b){a.U.kb?(b=new m0([0,
a.u.scrollTop],[0,b.BF.offsetTop],600,RVa),a.context.B.Ja(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ja(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.aG(a.U,!0),a.u.scrollTop=b.BF.offsetTop,g.aG(a.U,!1))},V0=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},yWa=function(a,b){return g.Db(a.cards,function(c){return c.card.id===b})},W0=function(a,b,c){L0.call(this,a,b);
this.annotation=c;this.isActive=!1},JWa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},X0=function(a,b,c){W0.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},KWa=function(a,b){var c=void 0===c?0:c;
var d=PVa(b).width;g.Ek(b,d);c=new o0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,QVa);g.J(a,c);a.context.B.Ja(c,"begin",function(){g.Nk(b,!0)});
c.play()},NWa=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ba:["iv-branding-context-name"],X:b.channel_name}),d=a.createElement({F:"div",Ba:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.JJ(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.ra(d));var f=a.createElement({F:"div",Ba:["iv-branding-context-subscribe-caret"]}),k=a.createElement({F:"div",Ba:["branding-context-container-inner"]});
k.appendChild(f);k.appendChild(c);k.appendChild(d);g.Nk(k,!1);var l=a.createElement({F:"div",Ba:["branding-context-container-outer"]});l.appendChild(k);g.yk(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.K(function(){LWa(a,k,l)},500);
g.J(a,a.B);a.context.j.Ja(a.element,"mouseover",function(){MWa(a,k,l,f,b.image_height)});
a.context.j.Ja(a.element,"mouseout",function(){a.B.start()})}},MWa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Mk(b);a.j||(b.style.width=g.Dk(f.width,!0),c.style.width=g.Dk(f.width,!0));g.yk(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.yk(d,"right","1px");a.C=!0;g.Nk(b,!0);a.D=new g.K(function(){g.sn(this.element,"iv-branding-active")},0,a);
a.D.start()}},LWa=function(a,b,c){g.un(a.element,"iv-branding-active");
a.I=new g.K(function(){g.Nk(b,!1);a.j||(c.style.width=g.Dk(0,!0))},250);
a.I.start();a.C=!1},OWa=function(a,b,c,d,e,f,k){this.j=a;
this.B=b;this.environmentData=c;this.videoData=d;this.logger=e;this.G=f;this.u=k},Y0=function(a,b,c){W0.call(this,a,b,c);
var d=this;this.P=this.isCollapsed=this.U=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ba:["iv-promo-contents"]});this.D=new g.K(function(){d.j.setAttribute("aria-hidden","true");g.Nk(d.B,!1);g.Nk(d.u,!0)},700,this);
g.J(this,this.D)},PWa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=pWa(a.annotation),f=b.image_url;if(f){var k=a.createElement({F:"div",Ba:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",T:{src:f,"aria-hidden":"true"}});k.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",L:"iv-promo-video-duration",X:b.video_duration}),k.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",L:"iv-promo-playlist-length",X:b.playlist_length.toString()}),k.appendChild(f));e&&M0(a,k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",L:"iv-promo-txt"}),g.wf(f,E0(e)),a.j=f):a.j=a.createElement({F:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",S:[{F:"strong",
X:b.text_line_1}]});var m=a.createElement({F:"p",S:[{F:"span",L:"iv-promo-link",X:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ba:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ba:["iv-button","iv-promo-button"],S:[{F:"span",L:"iv-button-content",X:f}]});var p=a.createElement({F:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&M0(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.sn(a.j,
"iv-click-target");e&&M0(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",S:[{F:"span",X:b.text_line_1}]}),m=a.createElement({F:"p",S:[{F:"strong",X:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ba:["yt-badge","iv-promo-badge-live"],X:"LIVE NOW"})),g.sn(a.j,"iv-click-target"),e&&M0(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&
a.J.appendChild(p);c=a.createElement({F:"div",L:"iv-promo-actions"});a.u=a.createElement({F:"button",Ba:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Ja(a.u,"click",function(q){Z0(a,5E3,q)});
c.appendChild(a.u);g.Nk(a.u,!1);a.context.j.Ja(a.element,"mouseover",a.sW,a);a.context.j.Ja(a.element,"mouseout",a.rW,a);a.context.j.Ja(a.element,"touchend",function(q){Z0(a,5E3,q)});
a.B=a.createElement({F:"button",Ba:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Ja(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.nW:a.mW,a);c.appendChild(a.B);g.tn(a.element,d);k&&(a.element.appendChild(k),n&&k.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},Z0=function(a,b,c){c.stopPropagation();
QWa(a);RWa(a,b);a.j.focus()},SWa=function(a){a.isCollapsed||a.P||a.C||(g.sn(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},QWa=function(a){a.D.stop();
a.isCollapsed&&(g.vn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Nk(a.u,!1),g.Nk(a.B,!0))},RWa=function(a,b){a.C||(a.C=g.Ig(function(){$0(this);
SWa(this)},b,a))},$0=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},TWa=function(a){this.G=a},AWa=function(a,b,c){b&&(c?a1(a,b.map(function(d){return g.dn(d,c)})):a1(a,b))},a1=function(a,b,c,d){var e=1,f=void 0,k=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(k),l=!0,c())};
k=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.ls(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},b1=function(a){g.EI.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new TWa(this.player);this.D=new g.Ry(this);this.C=this.Km=null;this.events=new g.Ry(this);this.J=this.j=null;this.P=[];g.J(this,this.D);this.D.N(this.player,"onVideoAreaChange",function(){b.W("onVideoAreaChange")});
this.D.N(this.player,"onHideControls",function(){b.W("onHideControls")});
this.D.N(this.player,"onShowControls",function(){b.W("onShowControls")});
this.D.N(this.player,"resize",function(d){b.W("resize",d)});
this.D.N(this.player,"presentingplayerstatechange",function(d){b.W("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.yU,this);this.subscribe("resize",this.BC,this);this.player.R().V.subscribe("vast_info_card_add",this.kQ,this);g.J(this,this.events);this.U=this.createElement({F:"div",L:"video-custom-annotations"});this.u=new g.V({F:"div",Ba:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.oI(this.player,this.u.element,4);this.u.hide();this.B=new g.V({F:"div",Ba:["ytp-iv-video-content"]});g.J(this,this.B);a=this.createElement({F:"div",L:"video-annotations"});
a.appendChild(this.U);this.B.element.appendChild(a);this.Js()&&this.load();var c=this.createElement({F:"style"});(g.Wf("HEAD")[0]||document.body).appendChild(c);g.de(this,function(){g.hg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},UWa=function(a){a=a.createElement({F:"div",
Ba:["annotation","annotation-type-custom"]});g.Nk(a,!1);return a},VWa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.aG(a.u,b);g.aG(a.B,b)},WWa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ka(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(WWa(a,e))}return c},ZWa=function(a){var b=a.player.getVideoData();
if(b.Qa){var c=a.player.R().V.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,k){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(k=g.Np(k)&&k.responseXML?k.responseXML:null)&&c1(a,k)}};
g.Qq()&&(d.onFinish=XWa(a,d.onFinish));d.postParams={ic_only:"1"};YWa(d,c);g.Tp(b.Qa,d)}}},YWa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.kx&&(a.postParams.ic_coll=b.kx);b.OA&&(a.postParams.ic_xml=b.OA);b.Pz&&(a.postParams.ic_track=b.Pz)},$Wa=function(a){var b=new g.V({F:"div"});
g.Nk(b.element,!1);var c=new Q0(a.player,b.element,d1(a));g.J(c,b);b.ra(a.u.element);c.Bz();return c},d1=function(a){if(!a.J){var b=new p0(a);
g.J(a,b);var c=new g.Ji(a);g.J(a,c);a.J=new OWa(b,c,a.player.R(),a.player.getVideoData(),a.logger,a.player,a.Ie)}return a.J},c1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ru();if(e){var f=g.qu();f&&g.wu(void 0,e,f,[g.ku(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=WWa(a,b[d]);e=null;try{if(f){var k=f.id,l=/.+/;var m="string"===typeof k&&null!=l&&null!=k&&k.match(l)?k:"";var n=D0(f.type,aXa),p=D0(f.style,bXa),q=gWa(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=mWa;if(null==u)var x=null;else if(g.Ia(u)){l=[];for(var y=g.r(u),z=y.next();!z.done;z=y.next()){var D=f(z.value);
D&&l.push(D)}x=l}else{var G=f(u);x=G?[G]:[]}e=m&&n?new nWa(m,n,p,x,t):null}else e=null}catch(ra){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=UWa(f),L=null;switch(l.type){case "branding":if(f.player.R().Kc)break;f.u.element.appendChild(H);L=new X0(H,d1(f),l);break;case "promotion":g.oI(f.player,H,4),L=new Y0(H,d1(f),l)}L&&L.Bz();if(f=L)g.J(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=$Wa(a),g.J(a,a.j));if("card"===e.type){c=a.j;var aa=e&&e.data&&e.data.card_type;
f=e.data;if(aa)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,AR:l.teaser_impression,xD:l.teaser_click},H=f.tracking_params||{},L=null,aa){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:H.card?g.ku(H.card):null,mj:H.teaser?g.ku(H.teaser):null,Ze:H.icon?g.ku(H.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:F0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};R0(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
Ql:H.card?g.ku(H.card):null,mj:H.teaser?g.ku(H.teaser):null,Ze:H.icon?g.ku(H.icon):null,thumbnailImageUrl:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:F0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};R0(c,e);break;case "productListing":f.signin_url&&(L=F0({target:"current",value:f.signin_url}));aa=[];for(var M=f.offers||[],ha=0;ha<M.length;ha++)aa.push(new sWa(g.Of(M[ha].merchant),
g.Of(M[ha].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:H.card?g.ku(H.card):null,mj:H.teaser?g.ku(H.teaser):null,Ze:H.icon?g.ku(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,jx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:F0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Vka:L,Uka:f.signin_title?f.signin_title:void 0,Tka:f.signin_message?f.signin_message:void 0,offers:aa,onClickCommand:null};R0(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:H.card?g.ku(H.card):
null,mj:H.teaser?g.ku(H.teaser):null,Ze:H.icon?g.ku(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,jx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:F0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};R0(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:H.card?g.ku(H.card):null,mj:H.teaser?g.ku(H.teaser):null,Ze:H.icon?g.ku(H.icon):null,thumbnailImageUrl:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:F0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},R0(c,e)}}else wWa(a.j,
e);c=!0}}c&&(h0(a.player),a.BC())},cXa=function(a,b){var c=!1;
a.j||(a.j=$Wa(a),g.J(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(xWa(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.nv(b.headerText):"",g.kg(c.Gb,d),c.P&&c.P.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ca=b.trackingParams?g.ku(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.ku(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ze=b.icon.infoCardIconRenderer.trackingParams?
g.ku(b.icon.infoCardIconRenderer.trackingParams):null,h0(a.player),a.BC())},dXa=function(a,b,c,d,e){if(!a.player.R().Kc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new jWa("openUrl","click",new hWa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.nv(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.nv(b.subscriberCountText))):(b.subscriberCountText&&(e=g.nv(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.nv(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.nv(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.nv(b.subscribedButtonText),unsubscribeCount:k||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new nWa(c,"branding","branding",f,d);l=UWa(a);a.u.element.appendChild(l);f=new X0(l,d1(a),f);f.Bz();g.J(f,f);a.I[c]=f}},XWa=function(a,b){return function(){var c=
g.za.apply(0,arguments);
a.isDisposed()||a.P.push(g.gn.Ug(function(){b.apply(null,g.v(c))}))}},eXa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.hI.prototype.Iv=g.ca(17,function(a,b){var c=g.VI(this.fb());c&&c.Iv(a,b)});
var j0={},k0=null;g.Ra(m0,g.Dn);g.h=m0.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.isPlaying())return!1;l0(this);this.startTime=a=g.Qa();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.xC();this.Dj("play");-1==this.j&&this.Dj("resume");this.j=1;var b=g.Ma(this);b in j0||(j0[b]=this);TVa();UVa(this,a);return!0};
g.h.stop=function(a){l0(this);this.j=0;a&&(this.progress=1);VVa(this,this.progress);this.Dj("stop");this.Ty()};
g.h.pause=function(){this.isPlaying()&&(l0(this),this.j=-1,this.Dj("pause"))};
g.h.Y=function(){0==this.j||this.stop(!1);this.Dj("destroy");m0.Ee.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.JE=function(){this.Dj("animate")};
g.h.Dj=function(a){this.dispatchEvent(new WVa(a,this))};
g.Ra(WVa,g.ee);g.Ra(n0,m0);n0.prototype.C=function(){};
n0.prototype.JE=function(){this.C();n0.Ee.JE.call(this)};
n0.prototype.Ty=function(){this.C();n0.Ee.Ty.call(this)};
n0.prototype.xC=function(){this.C();n0.Ee.xC.call(this)};
g.Ra(o0,n0);o0.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(p0,g.I);p0.prototype.Ja=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.Os(a,b,c);this.j.push(a);return a};
p0.prototype.hC=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.gqa(a,b,c);this.j.push(a);return a};
p0.prototype.qc=function(a){g.Ps(a);g.Ib(this.j,a)};
p0.prototype.Y=function(){g.Ps(this.j);this.j.length=0;g.I.prototype.Y.call(this)};g.w(t0,g.EI);g.h=t0.prototype;g.h.load=function(){g.EI.prototype.load.call(this);if(!u0(this)){var a=g.qya(this.player.getVideoData());a?(a=s0(a,YVa(this)),v0(this,a,!1)):ZVa(this)}};
g.h.unload=function(){v0(this,null);this.B&&(this.B.abort(),this.B=null);g.EI.prototype.unload.call(this)};
g.h.Xf=function(a,b){return u0(this)?"loadCustomEndscreenRenderer"===a?(a=s0(b,"new"),v0(this,a),!0):null:null};
g.h.getOptions=function(){return u0(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.ub=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<fXa.length;f++){var k=Math.abs(b.width-fXa[f]);if(-1===e||d>=k)e=f,d=k}d=gXa[e];this.u&&g.yk(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio,m=Math.round(k.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(k.left*a.width),p=a.top+Math.round(k.top*a.height);g.Lk(e.element,m,f);g.Ek(e.element,n,p);this.U&&(g.vn(e.element,hXa),256<m||256<f?g.sn(e.element,"ytp-ce-large-round"):96<m||96<f?g.sn(e.element,"ytp-ce-medium-round"):g.sn(e.element,"ytp-ce-small-round"));g.vn(e.element,iXa);m=k.left+k.width/2;k=k.top+l/2;g.sn(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":
.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.vn(e.element,gXa);g.sn(e.element,d);(e=g.Xf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.yk(e,"height",f+"px")}}}}};
g.h.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())C0(this,this.endscreen.impressionUrls),(a=g.ru())&&this.endscreen.visualElement&&g.xu(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.sn(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.sn(b,"ytp-ce-shown");C0(this,c.impressionUrls);(b=g.ru())&&g.xu(b,c.visualElement);this.player.R().B&&this.player.Ia("endscreenelementshown",
a)}};
g.h.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.un(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.un(b,"ytp-ce-shown");this.player.R().B&&this.player.Ia("endscreenelementhidden",a)}};
g.h.H_=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.vn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var fXa=[346,426,470,506,570,640,853,1280,1920],gXa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),iXa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],hXa=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var iWa={d7:"current",mda:"new"};var kWa={CLOSE:"close",Gda:"openUrl",SUBSCRIBE:"subscribe"},lWa={L3:"click",CLOSE:"close",J8:"hidden",rfa:"rollOut",sfa:"rollOver",tga:"shown"};var bXa={F2:"anchored",sS:"branding",CHANNEL:"channel",c7:"cta",M8:"highlightText",t$:"label",PLAYLIST:"playlist",Cea:"popup",Jga:"speech",SUBSCRIBE:"subscribe",mha:"title",VIDEO:"video",Sia:"website"},aXa={sS:"branding",y3:"card",x7:"drawer",L8:"highlight",eba:"marker",Mea:"promotion",TEXT:"text",xja:"widget"};g.w(L0,g.I);g.h=L0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.gv(a,b,{id:c,namespace:"annotations_module"});d&&this.Qa.set(a,d);e&&this.Sa.set(a,e);this.context.G.Sd([a])};
g.h.Bz=function(){this.context.u.subscribe("resize",this.JA,this)};
g.h.KE=function(a,b,c,d,e,f){if(this.ib)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.hg(this.element)};
g.h.JA=function(){};
g.h.navigate=function(a,b,c,d){var e=this,f=E0(a);if(f){var k=uWa(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.D||!1,n=g.Fp(f||"");m&&n&&(n.v||n.list)?e.context.G.ll(n.v,b,n.list,!1):g.lH(f||"","current"===k?"_top":void 0,b)};
"new"===k&&(l(),l=null);a1(this.context.logger,c,l,d);tWa(f)||(c=g.ru(),d=b.itct,c&&d&&g.Cu(c,g.ku(d)))}};
g.h.Y=function(){this.Qa.clear();this.Sa.clear();g.I.prototype.Y.call(this)};
g.h.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.w(Q0,L0);g.h=Q0.prototype;g.h.yp=function(){this.Z&&R0(this,this.Z)};
g.h.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Mk(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.JA=function(){var a=this.isAvailable();g.Nk(this.element,a);g.N(this.context.G.getRootNode(),g.kO.IV_DRAWER_ENABLED,a);h0(this.G)};
g.h.destroy=function(){this.G.Iv(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.ht(this.V);g.Ps(this.ma);this.Pa&&this.Pa.dispose();this.D&&this.D.dispose();L0.prototype.destroy.call(this)};
g.h.zV=function(){if(this.B){a1(this.context.logger,V0(this).tracking.close);var a=g.ru();a&&this.J&&g.Cu(a,this.J);P0(this)}};
g.h.MV=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.h.kX=function(){var a=g.ru(),b=V0(this);b=b?b.Ze:this.Ze;a&&b&&g.Au(a,[b])};
g.h.jX=function(){var a=g.ru(),b=V0(this);b=b?b.Ze:this.Ze;a&&b&&g.Bu(a,[b])};
g.h.xU=function(){var a=V0(this);a1(this.context.logger,a.tracking.AR);var b=g.ru();b&&a&&g.Au(b,[a.mj,a.Ze])};
g.h.lX=function(){var a=g.ru(),b=V0(this);a&&b&&g.Bu(a,[b.mj])};
g.h.wU=function(a){var b=V0(this),c=g.ru();this.j?a?(a=this.context.logger,a1(a,b.tracking.xD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.mj&&g.Cu(c,b.mj)):(a=this.context.logger,a1(a,b.tracking.xD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Ze&&g.Cu(c,b.Ze)):(a=this.context.logger,a1(a,b.tracking.xD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Ze&&g.Cu(c,this.Ze))};g.w(W0,L0);W0.prototype.Bz=function(){L0.prototype.Bz.call(this);JWa(this)};
W0.prototype.show=function(){L0.prototype.show.call(this);var a=g.ru(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Au(a,[g.ku(b.itct)])};
W0.prototype.hide=function(){L0.prototype.hide.call(this);var a=g.ru(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Bu(a,[g.ku(b.itct)])};g.w(X0,W0);
X0.prototype.show=function(){if(!this.isActive){W0.prototype.show.call(this);if(!this.J){g.sn(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ba:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Nk(this.u,!1);var b=this.context.environmentData.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Ba:["branding-img-container"]}):this.createElement({F:"button",Ba:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=pWa(this.annotation);c&&(b=this.context.environmentData.K("html5_player_branding_button_killswitch")?this.u:b,M0(this,b,c,this.annotation.id,a.session_data));NWa(this,a);this.J=!0}g.Nk(this.element,!0);this.isActive=!0;this.u&&KWa(this,this.u)}};
X0.prototype.hide=function(){this.isActive&&(W0.prototype.hide.call(this),g.Nk(this.element,!1),this.isActive=!1)};
X0.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);W0.prototype.destroy.call(this)};g.w(Y0,W0);g.h=Y0.prototype;g.h.show=function(){this.isActive||(W0.prototype.show.call(this),this.U||(PWa(this),this.U=!0),g.Nk(this.element,!0),g.Ig(function(){g.un(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,$0(this),QWa(this),RWa(this,this.I))};
g.h.hide=function(){this.isActive&&(g.sn(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.h.KE=function(a,b,c,d,e,f){return this.isCollapsed?!1:W0.prototype.KE.call(this,a,b,c,d,e,f)};
g.h.sW=function(a){this.P=!0;Z0(this,500,a)};
g.h.rW=function(){this.P=!1;SWa(this)};
g.h.mW=function(a){a.stopPropagation();this.hide()};
g.h.nW=function(a){a.stopPropagation();$0(this);this.isCollapsed=!0;g.sn(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();W0.prototype.destroy.call(this)};g.w(b1,g.EI);g.h=b1.prototype;g.h.Xf=function(a,b){if(!eXa(this.player.R().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.zZ(b))&&c1(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(zWa(this.j,b),h0(this.player)),!0}return null};
g.h.getOptions=function(){return eXa(this.player.R().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Js=function(){var a=this.player.R(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.KQ||a.V.get(b.videoId)||g.sD(b)||g.tD(b)?!0:!1};
g.h.BC=function(){if(this.B){var a=this.player.Wa().getVideoContentRect(!0);g.Lk(this.B.element,a.width,a.height);g.Ek(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Fj();a=this.j;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.h.yU=function(a){VWa(this,a.state);g.U(a.state,2)&&(this.Sh()&&this.Pl()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Iv(!1))};
g.h.load=function(){function a(k){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(k=g.Np(k)&&k.responseXML?k.responseXML:null)&&(c1(b,k),g.sn(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.EI.prototype.load.call(this);VWa(this,this.player.vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Qq()&&(a=XWa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.R().V.get(d);f&&YWa(e,f);f=f&&(f.OA||f.kx);if(!c.Ym||f)c.Qa?this.C=g.Tp(c.Qa,e):(this.Km=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Km));
g.oI(this.player,this.B.element,4);this.BC();(f=g.sD(c))&&cXa(this,f);(f=g.tD(c))&&f.featuredChannel&&dXa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.h.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Qa&&(this.Km&&(this.player.removeEventListener("videodatachange",this.Km),this.Km=null),this.C=g.Tp(b.Qa,a))};
g.h.unload=function(){this.player.yf("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,h0(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.EI.prototype.unload.call(this);this.B.detach();this.Km&&(this.player.removeEventListener("videodatachange",this.Km),this.Km=null)};
g.h.kQ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?ZWa(this):this.load())};
g.h.Sh=function(){return!!this.j&&this.j.isAvailable()};
g.h.Pl=function(){return!!this.j&&this.j.B};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Sh();this.j&&(a?c?O0(this.j,c,b):O0(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):P0(this.j))};
g.h.Iv=function(a,b){this.player.W(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.R().V.unsubscribe("vast_info_card_add",this.kQ,this);g.un(this.player.getRootNode(),g.kO.IV_DRAWER_OPEN);for(var a=this.P,b=g.gn,c=0,d=a.length;c<d;c++)b.Bj(a[c]);this.P.length=0;g.EI.prototype.Y.call(this)};
g.h.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.DI("annotations_module",b1);g.DI("creatorendscreen",t0);})(_yt_player);
