(function(g){var window=this;'use strict';var CZa=function(a,b){var c=[];return g.Dr(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},H3=function(a,b){return"getAll"in IDBIndex.prototype?g.rr(a.j.getAll(b,void 0)):CZa(a,b)},DZa=function(a,b){return g.xr(a,["captions"],{mode:"readonly",
jc:!0},function(c){return g.Soa(c.objectStore("captions"),b)})},EZa=function(a){var b=new g.ow("und",new g.Qy("Default","und",!0));
b.captionTracks=a.captionTracks;return b},FZa=function(a){return new g.wg(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},k=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.Fda(m,g.Pa(f,l),k);
else b(e)})},I3=function(a){this.j=a},J3=function(){I3.apply(this,arguments)},K3=function(){J3.apply(this,arguments)},L3=function(){J3.apply(this,arguments)},M3=function(){J3.apply(this,arguments)},N3=function(){I3.apply(this,arguments)},O3=function(){J3.apply(this,arguments)},P3=function(){J3.apply(this,arguments)},Q3=function(){J3.apply(this,arguments)},R3=function(){J3.apply(this,arguments)},S3=function(){J3.apply(this,arguments)},T3=function(){J3.apply(this,arguments)},U3=function(){J3.apply(this,
arguments)},V3=function(){I3.apply(this,arguments)},W3=function(){J3.apply(this,arguments)},X3=function(){J3.apply(this,arguments)},Y3=function(){J3.apply(this,arguments)},Z3=function(){J3.apply(this,arguments)},$3=function(){J3.apply(this,arguments)},a4=function(){J3.apply(this,arguments)},b4=function(){J3.apply(this,arguments)},c4=function(){I3.apply(this,arguments)},d4=function(){J3.apply(this,arguments)},e4=function(){J3.apply(this,arguments)},f4=function(){J3.apply(this,arguments)},g4=function(){J3.apply(this,
arguments)},h4=function(){J3.apply(this,arguments)},i4=function(){J3.apply(this,arguments)},j4=function(){J3.apply(this,arguments)},k4=function(){J3.apply(this,arguments)},l4=function(){J3.apply(this,arguments)},m4=function(){J3.apply(this,arguments)},n4=function(){J3.apply(this,arguments)},o4=function(){J3.apply(this,arguments)},p4=function(){J3.apply(this,arguments)},q4=function(){J3.apply(this,arguments)},r4=function(){J3.apply(this,arguments)},s4=function(){J3.apply(this,arguments)},t4=function(){J3.apply(this,
arguments)},u4=function(){J3.apply(this,arguments)},v4=function(){J3.apply(this,arguments)},w4=function(){J3.apply(this,arguments)},x4=function(){J3.apply(this,arguments)},y4=function(){J3.apply(this,arguments)},z4=function(){J3.apply(this,arguments)},A4=function(){J3.apply(this,arguments)},B4=function(){J3.apply(this,arguments)},C4=function(){J3.apply(this,arguments)},D4=function(){J3.apply(this,arguments)},E4=function(){J3.apply(this,arguments)},F4=function(){J3.apply(this,arguments)},G4=function(){J3.apply(this,
arguments)},H4=function(){J3.apply(this,arguments)},I4=function(){J3.apply(this,arguments)},J4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},GZa=function(){if(K4)return K4();
var a={};K4=g.fs("PersistentEntityStoreDb",{Wr:(a.EntityStore={Ko:1},a.EntityAssociationStore={Ko:2},a),shared:!1,upgrade:function(b,c){c(1)&&g.Ar(g.vr(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.vr(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.Ar(b,"byParentEntityKey","parentEntityKey"),g.Ar(b,"byChildEntityKey","childEntityKey"))},
version:3});return K4()},HZa=function(a){return g.Gr(GZa(),a)},L4=function(a,b){b=void 0===b?{}:b;
g.dr.call(this,g.rVa[a],Object.assign({},{name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,L4.prototype)},IZa=function(a){return new L4("WRONG_DATA_TYPE",{QV:a})},JZa=function(a){return a instanceof Error?new L4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new L4("UNKNOWN_ENCODE_ERROR")},KZa=function(a){return a instanceof Error?new L4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new L4("UNKNOWN_DECODE_ERROR")},LZa=function(a,b){a=a instanceof
L4?a:b(a);
g.R(a);throw a;},MZa=function(){},NZa=function(a,b,c){try{return a.B(b,c)}catch(d){LZa(d,JZa)}},M4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},N4=function(a){this.j=a},PZa=function(a){var b=OZa[a];
if(b)return b;g.hu(new g.dr("Entity model not found.",{entityType:a}))},QZa=function(a,b){this.j=a;
this.u=b;this.B={}},P4=function(a,b){a:{a=O4(a.u,b.version);
try{var c=a.u(b.data,b.key);break a}catch(d){LZa(d,KZa)}c=void 0}return c},Q4=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return P4(a,d)}})},R4=function(a,b,c){return c?(c=c.map(function(d){return Q4(a,d,b)}),g.pr.all(c)):H3(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return P4(a,e)})})},T4=function(a,b,c){var d=J4(b),e=O4(a.u,1),f=Object.assign({},b);
return a.j.objectStore("EntityStore").get(d).then(function(k){if(k){if(k.entityType!==c)throw Error("Incorrect entity type");f.entityMetadata||(k=P4(a,k),f.entityMetadata=k.entityMetadata)}}).then(function(){var k={key:d,
entityType:c,data:NZa(e,f,d),version:1};return g.pr.all([g.yr(a.j.objectStore("EntityStore"),k),RZa(a,f,c)])}).then(function(){S4(a,d,c);
return d})},U4=function(a,b,c){b=b.map(function(d){return T4(a,d,c)});
return g.pr.all(b)},V4=function(a,b,c){if(null==c?0:c.Xt){var d=new Set;
return SZa(a,b,d).then(function(){for(var f=[],k=g.r(d),l=k.next();!l.done;l=k.next())f.push(V4(a,l.value));return g.pr.all(f).then(function(){})})}var e=g.hC(b).entityType;
return g.pr.all([a.j.objectStore("EntityStore").delete(b),W4(a,b)]).then(function(){S4(a,b,e)})},TZa=function(a,b){return g.Dr(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.pr.all([c.delete(),
W4(a,c.FB())]).then(function(){S4(a,c.FB(),b);return c.continue()})})},S4=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},UZa=function(a,b,c){var d=J4(b);
c=PZa(c);if(!c)return g.pr.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.r(c.u());for(var e=c.next();!e.done;e=c.next())b.push(g.yr(a,{parentEntityKey:d,childEntityKey:e.value}));return g.pr.all(b).then(function(f){return f.map(function(k){return k[1]})})},W4=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},RZa=function(a,b,c){var d=J4(b);
return W4(a,d).then(function(){return UZa(a,b,c)})},SZa=function(a,b,c){if(c.has(b))return g.pr.resolve(void 0);
c.add(b);return VZa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.pr.resolve(void 0),f={};
d=g.r(d);for(var k=d.next();!k.done;f={UD:f.UD},k=d.next())f.UD=k.value,e=e.then(function(l){return function(){return SZa(a,l.UD,c)}}(f));
return e}).then(function(){})},VZa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return H3(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(H3(c.index("byChildEntityKey"),f.childEntityKey));return g.pr.all(e)}).then(function(d){var e=[];
d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},X4=function(){},WZa=function(){this.j={};
this.j[0]=new X4;if(!g.P("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.er();var c=M4(b);var d=new N4(new g.fA(c),new g.eA(c))}catch(e){throw a=e instanceof Error?new L4("KEY_CREATION_FAILED",{originalMessage:e.message}):new L4("KEY_CREATION_FAILED"),g.R(a),a;}a[1]=d}},O4=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new L4("INVALID_ENCODER_VERSION",{QV:b}),g.R(b),b;return a},Y4=function(a,b){g.I.call(this);
this.token=a;this.j=b;this.observers=[];a=new g.C.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.er());a.onmessage=this.u.bind(this);this.channel=a},Z4=function(a,b,c){var d,e,f,k;
return g.B(function(l){if(1==l.j)return g.A(l,HZa(a.token),2);if(3!=l.j)return d=l.u,g.A(l,g.xr(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new QZa(m,a.j);return c(e)}),3);
f=l.u;e&&(k=e.B,0<Object.keys(k).length&&(a.channel.postMessage(k),XZa(a,k)));return l.return(f)})},$4=function(a,b){a.observers.push(b);
return function(){var c=a.observers.indexOf(b);0<=c&&a.observers.splice(c,1)}},a5=function(a,b,c){return Z4(a,{mode:"readwrite",
jc:!0},function(d){return T4(d,b,c)})},YZa=function(a,b){return Z4(a,{mode:"readwrite",
jc:!0},function(c){return U4(c,b,"offlineOrchestrationActionWrapperEntity")})},ZZa=function(a,b){return Z4(a,{mode:"readwrite",
jc:!0},function(c){return V4(c,b)})},b5=function(a,b,c){return Z4(a,{mode:"readonly",
jc:!0},function(d){return Q4(d,b,c)})},c5=function(a,b,c){return Z4(a,{mode:"readonly",
jc:!0},function(d){return R4(d,b,c)})},XZa=function(a,b){a=g.r(a.observers);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},$Za=function(){var a,b,c;
return g.B(function(d){if(1==d.j)return g.sa(d,2),g.A(d,g.Nr(),4);if(2!=d.j){a=d.u;if(!a||!g.fr()||"undefined"===typeof g.C.BroadcastChannel)return d.return();b=new WZa;return d.return(new Y4(a,b))}c=g.ua(d);c instanceof Error&&g.R(c);return d.return()})},e5=function(){d5||(d5=$Za());
return d5},a_a=function(a){var b;
a=null==(b=a.options)?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},b_a=function(a){var b;
return g.B(function(c){return 1==c.j?g.A(c,e5(),2):(b=c.u)?g.A(c,Z4(b,"readwrite",function(d){for(var e={},f={},k=g.r(a),l=k.next();!l.done;f={ih:f.ih,nt:f.nt},l=k.next())f.ih=l.value,f.ih.entityKey&&a_a(f.ih)&&(f.nt=g.oe(f.ih.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.ih.type&&(l=function(m){return function(){return T4(d,m.ih.payload[m.nt],m.nt)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.ih.type&&(l=function(m){return function(){return V4(d,m.ih.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.ih.type&&(l=function(m){return function(){return d.updateEntity(m.ih.entityKey,m.ih.payload[m.nt],m.nt)}}(f)),l&&(e[f.ih.entityKey]=e[f.ih.entityKey]?e[f.ih.entityKey].then(l):l()));
return g.pr.all(Object.values(e))}),0):c.return()})},c_a=function(a){var b;
return g.B(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.YC){var d={type:"ENTITY_LOADED"};void 0!==b&&(d.payload=b);g.YC.dispatch(d)}return g.A(c,b_a(b),2)}b.length=0;g.qa(c)})},d_a=function(a){return void 0!==a},e_a=function(a){var b=g.sC();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.bxa(b);JSON.stringify(b);return b},f_a=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,g.Nr(),2);if(3!=d.j)return(b=d.u)?g.A(d,g.vC(b),3):d.return();c=d.u;return d.return(g.xr(c,["index","media","captions"],{mode:"readwrite",jc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.pr.all(e).then(function(){})}))})},g_a=function(){var a,b;
return g.B(function(c){if(1==c.j)return g.A(c,g.Nr(),2);if(3!=c.j){a=c.u;if(!a)throw g.nr("rvdfd");return g.A(c,g.vC(a),3)}b=c.u;return c.return(g.xr(b,["index","media"],{mode:"readwrite",jc:!0},function(d){var e={};return g.Br(d.objectStore("index"),{},function(f){var k=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),l=g.pr.resolve(void 0);if(k){var m=k[1];k=k[2];e[m]=e[m]||{};var n;e[m][k]=g.gxa(null==(n=f.getValue())?void 0:n.fmts)}else l=f.delete().then(function(){});
return g.pr.all([f.continue(),l]).then(function(p){return g.r(p).next().value})}).then(function(){for(var f={},k=g.r(Object.keys(e)),l=k.next();!l.done;l=k.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=e_a(f);return g.Voa(d.objectStore("media"),{},function(p){var q=p.getKey().match(g.kxa);q&&f[q[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},h_a=function(a,b){var c,d;
return g.B(function(e){if(1==e.j)return g.A(e,g.Nr(),2);if(3!=e.j){c=e.u;if(!c)throw g.nr("wct");return g.A(e,g.vC(c),3)}d=e.u;return g.A(e,g.xr(d,["captions"],{mode:"readwrite",jc:!0},function(f){var k=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.yr(f,b[l],a+"|"+b[l].metadata.vss_id);k.push(m)}return g.pr.all(k)}),0)})},i_a=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.A(e,g.Nr(),2);if(3!=e.j){c=e.u;if(!c)throw g.nr("gactfv");return g.A(e,g.vC(c),3)}d=e.u;return e.return(DZa(d,b))})},j_a=function(a){return g.B(function(b){g.uC(a,0);
return b.return(f_a(a))})},k_a=function(a){return{context:g.xF(),
videoIds:a}},l_a=function(a){return{context:g.xF(),
playlistIds:a}},f5=function(a,b,c){g.hu(new g.dr("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.hu(b)},m_a=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,u,x,y,z,D;
return g.B(function(G){if(1==G.j)return g.A(G,Z4(a,{mode:"readonly",jc:!0},function(H){return R4(H,"playbackData").then(function(L){var aa=L.map(function(ha){return ha.transfer}).filter(function(ha){return!!ha}),M=L.map(function(ha){return ha.offlineVideoPolicy}).filter(function(ha){return!!ha});
aa=R4(H,"transfer",aa);M=R4(H,"offlineVideoPolicy",M);return g.pr.all([aa,M]).then(function(ha){var ra=g.r(ha);ha=ra.next().value;ra=ra.next().value;return[L,ha,ra]})})}),2);
b=G.u;c=g.r(b);d=c.next().value;e=c.next().value;f=c.next().value;k=d;l=e;m=f;n={};p={};q=g.r(l);for(t=q.next();!t.done;t=q.next())(u=t.value)&&(n[u.key]=u);x=g.r(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);D=k.map(function(H){var L=n[H.transfer],aa=p[H.offlineVideoPolicy];H=g.hC(aa.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===aa.action){var M="OFFLINE_VIDEO_STATE_DISABLED";aa.expirationTimestamp&&Number(aa.expirationTimestamp)<Date.now()/1E3&&(M="OFFLINE_VIDEO_STATE_EXPIRED");
aa=M}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===aa.action)aa="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null==L?void 0:L.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":M="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":M="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":M="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":M="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":M=
"OFFLINE_VIDEO_STATE_PLAYABLE";break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":M="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:M="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===M)switch(null==L?void 0:L.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":M="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":M="OFFLINE_VIDEO_STATE_STREAMS_MISSING";
break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":M="OFFLINE_VIDEO_STATE_NETWORK_ERROR"}aa=M}H={id:H,videoState:aa};if(null==L?0:L.cotn)H.cotn=L.cotn;if(null==L?0:L.maximumDownloadQuality)H.selectedVideoQuality=null==L?void 0:L.maximumDownloadQuality;return H});
return G.return({offlineVideos:D})})},n_a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,m_a(a),2);b=c.u;g.Xq("offlineStateSnapshot",b);g.qa(c)})},g5=function(a){g.I.call(this);
this.api=a;"undefined"!==typeof g.C.BroadcastChannel&&(this.j=new g.C.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.er()),this.j.onmessage=this.B.bind(this),this.u=new g.C.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.er()),this.u.onmessage=this.C.bind(this))},h5=function(a,b){a.api.Ia("onOfflineOperationFailure",b);
var c;null==(c=a.j)||c.postMessage(b)},o_a=function(){this.locks=navigator.locks},p_a=function(){try{var a=g.Fa("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.C.localStorage&&g.C.localStorage.getItem("noop"),a=new o_a,g.Ea("ytglobal.locks_",a),a}catch(d){}},r_a=function(a,b,c,d){var e=this;
this.P=a;this.U=b;this.visibility=c;this.K=d;this.C=this.I=this.D=this.u=this.j=!1;this.J=new g.K(function(){q_a(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.qf()})},s_a=function(a){if(!a.u&&!a.j){var b=p_a();
if(b){a.u=!0;var c=g.er("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f,k;return g.B(function(l){switch(l.j){case 1:return g.sa(l,2),a.B=new g.Rh,a.j=!0,a.u=!1,g.A(l,a.P(),4);case 4:return g.A(l,a.B.promise,5);case 5:g.ta(l,0);break;case 2:d=g.ua(l),(null==(f=(e=a).K)?0:f.call(e,"wo_relinquish_leadership_on_lock_request_error"))||q_a(a),d instanceof Error&&(k=d,k.args=[{name:"WoLockManagerError",IC:d.name}],g.R(k)),g.qa(l)}})})}}},t_a=function(a){a.j&&(a.C=
!0,i5(a))},u_a=function(a,b){a.j&&(a.D=b,i5(a))},v_a=function(a,b){a.j&&(a.I=b,i5(a))},i5=function(a){a.I&&a.D&&a.C&&a.visibility.isBackground()?g.ln(a.J,6E4):a.J.stop()},q_a=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.U()},j5=function(a,b){var c=b.pj;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;var d;a.isRefresh=null!=(d=c.isRefresh)?d:!1;var e;a.softErrorCount=null!=(e=c.transferRetryCount)?e:0;g.Xq("offlineTransferStatusChanged",a)},w_a=function(a,b,c,d){b=Math.floor(b/1024).toFixed();
j5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",transferFirstStarted:!!d,alreadyDownloadedKbytes:b,totalFetchedKbytes:b,totalContentKbytes:Math.floor(c/1024).toFixed()},a)},x_a=function(a){j5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},y_a=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
k5=function(){},l5=function(){},m5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.er("CacheStorage get")},z_a=function(){return g.B(function(a){if(void 0!==n5)return a.return(n5);
n5=new Promise(function(b){var c;return g.B(function(d){switch(d.j){case 1:return g.sa(d,2),g.A(d,o5.open("test-only"),4);case 4:return g.A(d,o5.delete("test-only"),5);case 5:g.ta(d,3);break;case 2:if(c=g.ua(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.qa(d)}})});
return a.return(n5)})},q5=function(){return g.B(function(a){if(1==a.j)return g.A(a,z_a(),2);
if(!a.u)return a.return(void 0);p5||(p5=new l5);return a.return(p5)})},A_a=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,q5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},r5=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,q5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},s5=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,q5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,c.addAll(a),0)})},t5=function(a){var b,c,d;
return 0<(null!=(d=null==(b=a.actionMetadata)?void 0:null==(c=b.retryScheduleIntervalsInSeconds)?void 0:c.length)?d:0)},u5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},v5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},w5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&!!a.entityKey},A5=function(a,b,c,d){var e,f,k,l,m,n,p,q,t,u,x,y,z,D,G,H,L,aa,M,ha,ra,X,oa,Ja,Sa,Za,eb,Vb;
return g.B(function(Wb){switch(Wb.j){case 1:return e=g.iC(a,"ytMainVideoEntity"),f=g.iC(a,"mainVideoEntity"),k=g.iC(a,"ytMainChannelEntity"),l=g.iC(a,"transfer"),g.A(Wb,Z4(b,{mode:"readonly",jc:!0},function(fc){return g.pr.all([Q4(fc,e,"ytMainVideoEntity"),Q4(fc,f,"mainVideoEntity"),Q4(fc,k,"ytMainChannelEntity"),Q4(fc,l,"transfer"),R4(fc,"ytMainChannelEntity"),R4(fc,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:m=Wb.u;n=g.r(m);p=n.next().value;q=n.next().value;t=n.next().value;u=n.next().value;x=n.next().value;y=n.next().value;z=p;D=q;G=t;H=u;L=x;aa=y;if(!(z||D||G)){Wb.Oa(3);break}M=z?x5(z.thumbnail):D?x5(D.thumbnail):[];if(!G){ha=[];Wb.Oa(4);break}return g.A(Wb,B_a(G,L),5);case 5:ha=Wb.u;case 4:return ra=ha,g.A(Wb,r5(M.concat(ra)),3);case 3:X=[];oa=g.iC(a,"ytMainDownloadedVideoEntity");Ja=g.iC(a,"mainVideoEntity");Sa=g.r(aa);for(Za=Sa.next();!Za.done;Za=Sa.next())eb=Za.value,Vb=g.hC(eb.key).entityId,
Vb!==a||y5(c,eb.actionProto)||X.push(eb.key);return g.A(Wb,Z4(b,{mode:"readwrite",jc:!0},function(fc){var Na=X.map(function(jc){return V4(fc,jc)});
Na.push(V4(fc,oa,{Xt:!0}));Na.push(V4(fc,Ja,{Xt:!0}));return g.pr.all(Na)}),7);
case 7:z5(H),h5(d,{entityKey:oa,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),h5(d,{entityKey:Ja,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.qa(Wb)}})},E_a=function(a,b,c,d){var e,f,k,l,m,n,p,q,t,u,x,y,z,D,G,H,L,aa,M,ha,ra,X,oa,Ja,Sa,Za,eb,Vb,Wb,fc;
return g.B(function(Na){switch(Na.j){case 1:return e=g.iC(a,"mainPlaylistEntity"),f=g.iC(a,"ytMainChannelEntity"),g.A(Na,Z4(b,{mode:"readonly",jc:!0},function(jc){return g.pr.all([Q4(jc,e,"mainPlaylistEntity"),Q4(jc,f,"ytMainChannelEntity"),R4(jc,"mainPlaylistEntity"),R4(jc,"ytMainChannelEntity"),R4(jc,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:k=Na.u;l=g.r(k);m=l.next().value;n=l.next().value;p=l.next().value;q=l.next().value;t=l.next().value;u=m;x=n;y=p;z=q;D=t;if(!u&&!x){Na.Oa(3);break}G=u?C_a(u):[];if(!x){H=[];Na.Oa(4);break}return g.A(Na,B_a(x,z),5);case 5:H=Na.u;case 4:return L=H,g.A(Na,r5(G.concat(L)),3);case 3:if(!u){Na.Oa(7);break}return g.A(Na,D_a(u,y),8);case 8:aa=Na.u;if(!aa){Na.Oa(7);break}M=g.r(aa);ha=M.next();case 10:if(ha.done){Na.Oa(7);break}ra=ha.value;X=JSON.parse(g.hC(ra).entityId);oa=X.videoId;Ja=X.playlistId;
if(!oa||Ja!==u.playlistId){Na.Oa(11);break}return g.A(Na,A5(oa,b,c,d),11);case 11:ha=M.next();Na.Oa(10);break;case 7:Sa=[];Za=g.r(D);for(eb=Za.next();!eb.done;eb=Za.next())Vb=eb.value,Wb=g.hC(Vb.key).entityId,Wb!==a||y5(c,Vb.actionProto)||Sa.push(Vb.key);fc=g.iC(a,"mainPlaylistEntity");return g.A(Na,Z4(b,{mode:"readwrite",jc:!0},function(jc){var Vd=Sa.map(function(Qe){return V4(jc,Qe)});
Vd.push(V4(jc,fc,{Xt:!0}));return g.pr.all(Vd)}),0)}})},B5=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,Z4(a,{mode:"readwrite",jc:!0},function(p){var q=R4(p,"transfer"),t=R4(p,"offlineOrchestrationActionWrapperEntity");return g.pr.all([q,t]).then(function(u){u=g.r(u);var x=u.next().value,y=u.next().value;u=F_a.map(function(L){return TZa(p,L)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var D=g.hC(z.actionProto.entityKey).entityType,G="ytMainDownloadedVideoEntity"===D;D="mainVideoEntity"===D;var H="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;y5(b,z.actionProto)||G&&(!G||H)&&D&&(!D||H)||u.push(V4(p,z.key,{Xt:!0}))}return g.pr.all(u).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())k=f.value,z5(k),l=g.hC(k.key).entityId,m=g.iC(l,"ytMainDownloadedVideoEntity"),h5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,A_a(),0)})},H_a=function(a,b,c,d){var e,f,k,l,m,n,p,q,t,u,x,y,z,D,G,H,L,aa,M,ha,ra,X,oa,Ja;
return g.B(function(Sa){switch(Sa.j){case 1:return e=g.iC(a,"musicTrack"),f=g.iC(a,"musicArtist"),k=g.iC(a,"transfer"),g.A(Sa,Z4(b,{mode:"readonly",jc:!0},function(Za){return g.pr.all([Q4(Za,e,"musicTrack"),Q4(Za,f,"musicArtist"),Q4(Za,k,"transfer"),R4(Za,"musicArtist"),R4(Za,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:l=Sa.u;m=g.r(l);n=m.next().value;p=m.next().value;q=m.next().value;t=m.next().value;u=m.next().value;x=n;y=p;z=q;D=t;G=u;if(!x&&!y){Sa.Oa(3);break}H=x?x5(x.thumbnailDetails):[];if(!y){L=[];Sa.Oa(4);break}return g.A(Sa,G_a(y,D),5);case 5:L=Sa.u;case 4:return aa=L,g.A(Sa,r5(H.concat(aa)),3);case 3:M=[];ha=g.iC(a,"musicTrack");ra=g.r(G);for(X=ra.next();!X.done;X=ra.next())oa=X.value,Ja=g.hC(oa.key).entityId,Ja!==a||y5(c,oa.actionProto)||M.push(oa.key);return g.A(Sa,Z4(b,{mode:"readwrite",jc:!0},
function(Za){var eb=M.map(function(Vb){return V4(Za,Vb)});
eb.push(V4(Za,ha,{Xt:!0}));return g.pr.all(eb)}),7);
case 7:z5(z),h5(d,{entityKey:ha,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.qa(Sa)}})},I_a=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,Z4(a,{mode:"readwrite",jc:!0},function(p){var q=R4(p,"transfer"),t=R4(p,"offlineOrchestrationActionWrapperEntity");return g.pr.all([q,t]).then(function(u){u=g.r(u);var x=u.next().value,y=u.next().value;u=F_a.map(function(H){return TZa(p,H)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var D="musicTrack"===g.hC(z.actionProto.entityKey).entityType,G="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;y5(b,z.actionProto)||D&&(!D||G)||u.push(V4(p,z.key,{Xt:!0}))}return g.pr.all(u).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())k=f.value,z5(k),l=g.hC(k.key).entityId,m=g.iC(l,"ytMainDownloadedVideoEntity"),h5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,A_a(),0)})},y5=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},z5=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.hC(a.key).entityId;
j5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,pj:a})}},x5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.r(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},C_a=function(a,b){var c=[];
if(a.thumbnailStyleData){a=g.r(a.thumbnailStyleData);for(var d=a.next();!d.done;d=a.next()){var e=void 0,f=void 0,k=void 0;c=c.concat(x5(null==(e=d.value)?void 0:null==(f=e.value)?void 0:null==(k=f.collageThumbnail)?void 0:k.coverThumbnail))}}b=x5(b);return c.concat(b)},D_a=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u;
return g.B(function(x){c=[];if(a.videos){d=g.r(a.videos);for(e=d.next();!e.done;e=d.next())f=e.value,c.push(f);k=g.r(b);for(l=k.next();!l.done;l=k.next())if(m=l.value,m.key!==a.key&&(n=m.videos))for(p=g.r(n),q=p.next();!q.done;q=p.next())t=q.value,u=c.indexOf(t),-1!==u&&c.splice(u,1)}return x.return(c)})},B_a=function(a,b){var c,d,e,f,k,l,m,n;
return g.B(function(p){c=x5(a.avatar);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(k=g.r(x5(f.avatar)),l=k.next();!l.done;l=k.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},G_a=function(a,b){var c,d,e,f,k,l,m,n;
return g.B(function(p){c=x5(a.thumbnailDetails);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(k=g.r(x5(f.thumbnailDetails)),l=k.next();!l.done;l=k.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},C5=function(a){this.j=a},J_a=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=new Map,d=g.r(b),e=d.next();case 2:if(e.done){n.Oa(4);break}f=e.value;k=c;l=k.set;m=f;return g.A(n,a.u(f),5);case 5:l.call(k,m,n.u);e=d.next();n.Oa(2);break;case 4:return n.return(c)}})},D5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},E5=function(a,b,c){this.j=a;
this.environmentData=b;this.B=c},M_a=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=b.entityKey;f=null==(d=b.actionMetadata)?void 0:null==(e=d.playbackDataActionMetadata)?void 0:e.isEnqueuedForExpiredStreamUrlRefetch;g.sa(n,2);var p;var q=null!=(p=b.actionMetadata)&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.A(n,K_a(a,c,{isEnqueuedForExpiredStreamUrlRefetch:f,fS:q}),4);case 4:return(k=n.u)?g.A(n,L_a(a,k,b),5):n.return(F5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 5:return n.return(F5(b,!0,k.orchestrationActions));case 2:return l=g.ua(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.ir&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),f5("PDE handleAdd error"),n.return(F5(b,!1,void 0,m))}})},N_a=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u,x,y,z;
return g.B(function(D){switch(D.j){case 1:return c=b.entityKey,g.A(D,Z4(a.j,{mode:"readonly",jc:!0},function(G){var H=Q4(G,c,"playbackData"),L=Q4(G,g.iC(g.hC(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");G=Q4(G,g.iC(g.hC(b.entityKey).entityId,"transfer"),"transfer");return g.pr.all([H,L,G])}),2);
case 2:d=D.u;e=g.r(d);f=e.next().value;k=e.next().value;l=e.next().value;m=f;n=k;p=l;if(!m||!n)return D.return(F5(b,!0));q={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null==(u=p)?0:u.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.sa(D,3);return g.A(D,K_a(a,c,{refreshData:q,fS:t}),5);case 5:return(x=D.u)?g.A(D,L_a(a,x,b),6):D.return(F5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 6:return D.return(F5(b,
!0,x.orchestrationActions));case 3:return y=g.ua(D),z="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",y instanceof g.ir&&"QUOTA_EXCEEDED"===y.type&&(z="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),D.return(F5(b,!1,void 0,z))}})},K_a=function(a,b,c){var d,e,f;
return g.B(function(k){d=g.HH();var l=a.environmentData,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.fS,q={entityKey:b};m&&(q.refreshData=m);n&&(q.isExpiredStreamUrlRefetch=n);p&&(q.downloadParameters=p);e={context:g.VH(l),signatureTimestamp:19159,videos:[q]};f=g.sH(O_a);return k.return(g.DF(d,e,f))})},L_a=function(a,b,c){var d;
return g.B(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.Oa(2);d=g.hC(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.A(e,A5(d,a.j,c,a.B),2)}return g.A(e,c_a(b.frameworkUpdates.entityBatchUpdate),0)})},F5=function(a,
b,c,d){return new D5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",t5(a),c,d)},G5=function(){C5.apply(this,arguments)},Q_a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.A(e,b5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.sa(e,3);return g.A(e,P_a(a,b),5);case 5:g.ta(e,4);break;case 3:return g.ua(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},R_a=function(a,b){var c,
d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.A(e,b5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.sa(e,3);return g.A(e,P_a(a,b,!0),5);case 5:g.ta(e,4);break;case 3:return g.ua(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},P_a=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return e=null==(d=b.actionMetadata)?void 0:d.transferEntityActionMetadata,l={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.nu(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null==(f=e)?void 0:f.maximumDownloadQuality,preferredAudioTrack:null==(k=e)?void 0:k.preferredAudioTrack,transferRetryCount:0,isRefresh:c,hasLoggedFirstStarted:!1},m=g.hC(l.key).entityId,g.A(n,Z4(a.j,{mode:"readwrite",jc:!0},function(p){var q=
[];c&&q.push(V4(p,g.iC(m,"offlineVideoStreams")));q.push(T4(p,l,"transfer"));return g.pr.all(q)}),2);
j5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:m,pj:l});g.qa(n)})},S_a=function(a,b,c){return new g.PC(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},T_a=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},H5=function(a,b,c,d,e,f,k,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=k;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},I5=function(a){return{key:g.iC(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},U_a=function(){this.j=new Map},V_a=function(){J5||(J5=new U_a);
return J5},W_a=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0,can:void 0}},X_a=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.nu(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);b.can&&(a.can=b.can);g.Xq("flowEvent",a,void 0)},Y_a=function(a,b,c,d){if(!a.action.entityKey)throw Error("entityKey is missing.");
var e=g.hC(a.action.entityKey);a={entityType:e.TV,entityId:e.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=c?!1:b.j);d&&(a.additionalOrchestrationActions=d.map(function(f){return{orchestrationActionId:f.actionId}}));
return a},K5=function(a,b){var c={offlineOrchestrationContext:Y_a(a)};
b=W_a(b,c);X_a(V_a(),b,a.rootActionId)},L5=function(a,b,c,d){d=void 0===d?[]:d;
b={offlineOrchestrationContext:Y_a(a,b,c,d)};b=W_a(3,b);X_a(V_a(),b,a.rootActionId)},Z_a=function(){this.actions=[]},$_a=function(a,b){b=g.r(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,K5(c,1),a.actions.push(c);a.actions.sort(a.j)},a0a=function(a,b){a=g.r(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},M5=function(a,b,c,d){g.I.call(this);
var e=this;this.u=a;this.Z=b;this.U=c;this.D=d;this.j=new Z_a;this.P=new g.ts;this.C=new g.K(function(){e.retry()});
this.I=NaN;g.J(this,this.C);this.J=$4(this.u,this.V.bind(this))},c0a=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return e=new M5(a,b,c,d),g.A(f,b0a(e),2);e.B?Promise.resolve():N5(e);return f.return(e)})},N5=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,u,x,y;
return g.B(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();u_a(a.U,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.Z[b.entityType]){z.Oa(2);break}a.B=void 0;return g.A(z,N5(a),3);case 3:return z.return();case 2:f=g.r(c);for(k=f.next();!k.done;k=f.next())l=k.value,K5(l,2);g.sa(z,4,
5);return g.A(z,J_a(e,c.map(function(D){return D.action})),7);
case 7:m=z.u,n=g.r(c),k=n.next();case 8:if(k.done){z.Oa(5);break}p=k.value;q=m.get(p.action);return g.A(z,d0a(a,p,q),9);case 9:k=n.next();z.Oa(8);break;case 5:g.va(z);a.B=void 0;g.wa(z,6);break;case 4:return t=g.ua(z),f5("Orchestration error",t),g.sa(z,12),g.A(z,e0a(a,c),14);case 14:g.ta(z,5);break;case 12:u=g.ua(z);f5("Orchestration retry error",u);x=g.r(c);for(k=x.next();!k.done;k=x.next())y=k.value,3>y.retryScheduleIndex&&$_a(a.j,[y]);z.Oa(5);break;case 6:return g.A(z,N5(a),0)}})},d0a=function(a,
b,c){var d,e,f,k,l,m,n;
return g.B(function(p){if(1==p.j){d=3===b.retryScheduleIndex+2;if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){l=void 0;try{l=null==(m=c.u)?void 0:m.map(function(q){return a.createAction(q,b)})}catch(q){return L5(b,c,d),n={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},h5(a.D,n),f5("Orchestration subactions creation error",q),p.return()}L5(b,c,d,l);return g.A(p,Z4(a.u,{mode:"readwrite",jc:!0},function(q){var t=[];if(l){var u=l.map(function(x){return I5(x)});
t.push(U4(q,u,"offlineOrchestrationActionWrapperEntity"))}u=I5(b);t.push(V4(q,u.key));return g.pr.all(t)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return p.Oa(0);
L5(b,c,d);if(c.j&&3>b.retryScheduleIndex+1)return g.A(p,e0a(a,[b]),0);f=(null==(e=c)?0:e.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";k={entityKey:b.action.entityKey,failureReason:f};h5(a.D,k);f5("Orchestration result is not retryable, deleting action");return g.A(p,ZZa(a.u,I5(b).key),0)}K5(b,4);g.qa(p)})},O5=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u;
return g.B(function(x){c=[];d=Infinity;e=4E3;f=g.r(b);for(k=f.next();!k.done;k=f.next())l=k.value,m=Number(l.enqueueTimeSec),n=f0a(m),p=l.retryScheduleIndex,q=null!=p&&0<p,0<n&&q?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.I)&&(a.I=d,a.C.start(e));a.P.mf()||(t=c.length,c=c.filter(function(y){var z;y=(null==(z=y.actionProto)?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!g0a.includes(y)}),u=c.length<t,!a.C.isActive()&&u&&a.C.start(1));
0<c.length&&h0a(a,c);return g.A(x,a.B?Promise.resolve():N5(a),0)})},j0a=function(a){var b,c,d,e,f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,i0a(a),2);b=m.u;c=[];d=g.r(b);for(e=d.next();!e.done;e=d.next())f=e.value,k=g.hC(f.key),l=k.entityId,a0a(a.j,l)||c.push(f);return g.A(m,O5(a,c),0)})},f0a=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},e0a=function(a,b){var c,d,e;
return g.B(function(f){c=g.r(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var k=void 0,l=void 0,m=(null==(l=e.action)?void 0:null==(k=l.actionMetadata)?void 0:k.retryScheduleIntervalsInSeconds)||[1,2,4];k=1;e.retryScheduleIndex<m.length&&(k=m[e.retryScheduleIndex]);e.j=1E3*k+Date.now();e.retryScheduleIndex++}return g.A(f,k0a(a,b),0)})},b0a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,c5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.A(c,O5(a,b),0)})},h0a=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.hC(c.key),e=g.hC(c.actionProto.entityKey);c=new H5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&$_a(a.j,[c])})},i0a=function(a,b){var c;
return g.B(function(d){if(1==d.j)return g.A(d,c5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(d_a))})},k0a=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return I5(c)});
return YZa(a.u,b)},l0a=function(){this.j=void 0},n0a=function(a,b){var c,d,e,f,k;
return g.B(function(l){c=b.videoId;d=b.R();e=!0;if(b.captionTracks.length)f=EZa(b),a.j=new g.II(d,b,f);else if(b.Hc)k=g.wya(b),a.j=new g.KI(d,b.Hc,c,k,b.rl),e=b.rl;else return l.return();return l.return(new Promise(function(m){var n;null==(n=a.j)||n.Yu(function(){return g.B(function(p){if(1==p.j)return g.A(p,m0a(a,c,e),2);m();g.qa(p)})})}))})},m0a=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,k,l,m,n,p,q,t,u,x,y,z;return g.B(function(D){switch(D.j){case 1:if(!a.j)return D.return();d=[];e=g.FI(a.j.u,c);f=[];k={};l=g.r(e.entries());for(m=l.next();!m.done;k={QD:k.QD},m=l.next())n=m.value,p=g.r(n),q=p.next().value,t=p.next().value,k.QD=q,u=t,x=a.j.yr(u,"json3"),y=g.Wp(x,{withCredentials:!0,format:"RAW"},3,500).then(function(G){return function(H){H={metadata:g.AC(e[G.QD]),trackData:H.xhr.responseText};f.push(H)}}(k)).Ji(function(G){f5("Caption fetch error",G)}),d.push(y);
return g.A(D,FZa(d),2);case 2:return g.sa(D,3),g.A(D,h_a(b,f),5);case 5:g.ta(D,0);break;case 3:z=g.ua(D),f5("Caption DB transaction error",z),g.qa(D)}})},o0a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,i_a(a),2);b=c.u;return c.return(!!b&&0<b.length)})},p0a=function(a,b){this.api=a;
this.j=b;this.logger=new g.bO("woffle");this.u=!1},q0a=function(a){return g.B(function(b){return b.return(j_a(a))})},r0a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,g.hxa(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},P5=function(a,b){var c=g.tC(b);
if(1===c||0===c)return Promise.resolve();(c=s0a(a,b))&&c.stopVideo();a.B=0;return q0a(b)},Q5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.tC(e)&&((b=s0a(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.uC(e,2),a.B=2,c?t0a(a.j):d&&u0a(a.j))},s0a=function(a,b){var c;
return(null==(c=a.player)?void 0:c.getVideoData().videoId)===b?a.player:null},v0a=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},R5=function(a){g.I.call(this);
this.j=a;this.u=$4(this.j,this.B.bind(this))},w0a=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.iC(p,"transfer")});
return g.A(n,c5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(d_a).map(function(p){return g.hC(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);k=g.r(f);l=k.next();case 3:if(l.done){n.Oa(5);break}m=l.value;return g.A(n,q0a(m),4);case 4:l=k.next();n.Oa(3);break;case 5:return n.return(f)}})},y0a=function(a,b,c,d,e,f){var k,l,m;
return g.B(function(n){k="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(k="STREAM_TYPE_AUDIO_AND_VIDEO",f5("unexpected stream type")):c.video&&!c.audio?k="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(k="STREAM_TYPE_AUDIO");l=g.iC(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:k,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===k?Number(c.Tb()):void 0};return g.A(n,Z4(a,{mode:"readwrite",jc:!0},
function(p){var q=Q4(p,l,"offlineVideoStreams"),t=Q4(p,g.iC(b,"transfer"),"transfer");return g.pr.all([q,t]).then(function(u){var x=g.r(u);u=x.next().value;x=x.next().value;if(!x)return V4(p,l).then(function(){});
u=[T4(p,x0a(u,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),u.push(T4(p,x,"transfer")));return g.pr.all(u)})}),0)})},z0a=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.iC(b,"offlineVideoStreams"),g.A(l,b5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.r(d.streamsProgress);for(f=e.next();!f.done;f=e.next())k=f.value,k.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",k.numTotalBytes!==k.numBytesDownloaded&&(k.numBytesDownloaded=k.numTotalBytes);return g.A(l,a5(a,d,"offlineVideoStreams"),0)})},x0a=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var k=JSON.parse(e[f].formatStreamBytes);if(k.itag+";"+k.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},S5=function(a,b,c,d){g.I.call(this);
var e=this;this.u=a;this.api=b;this.ya=c;this.ma=d;this.D=new g.ts;this.C=new g.K(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.mf()&&(3>(e.j.transferRetryCount||0)?Q5(e.I,e.B,!1,!1):P5(e.I,e.B.videoDetails.videoId),e.Zr("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.U=0;this.ea=new g.Ry(this);this.J=$4(this.u,this.SS.bind(this));this.I=new p0a(b,this);this.Ga=new l0a;this.P=new R5(this.u);this.Z=this.D.Ja("publicytnetworkstatus-online",this.sz.bind(this));this.V=this.D.Ja("publicytnetworkstatus-offline",this.N_.bind(this));g.J(this,this.ea);this.ea.N(b,"offlinetransferpause",this.O_);this.Ca=g.Lz(this.api.R().experiments,"web_player_transfer_timeout_threshold_ms")},A0a=function(a){return g.B(function(b){if(1==b.j)b=g.A(b,g_a(),2);
else{var c=a.P;var d=g.sC();d=Object.keys(d);c=w0a(c,d);b=g.A(b,c,0)}return b})},U5=function(a,b){b=void 0===b?!1:b;
var c;return g.B(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.A(d,B0a(a),2)}return 4!=d.j?(c=d.u,v_a(a.ya,!c),c&&a.D.mf()?b?g.A(d,new Promise(function(e){g.Op(e,1E3)}),4):d.Oa(4):(!c&&a.j&&T5(a),d.Oa(0))):g.A(d,C0a(a,c),0)})},D0a=function(a){return g.B(function(b){if(1==b.j)return a.B?g.A(b,P5(a.I,a.B.videoDetails.videoId),3):b.Oa(0);
T5(a);g.qa(b)})},E0a=function(a,b){var c,d,e;
return g.B(function(f){switch(f.j){case 1:return g.sa(f,2),(c=!!b.captionTracks.length||!!b.Hc)?g.A(f,o0a(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.A(f,n0a(a.Ga,b),5);case 5:g.ta(f,0);break;case 2:e=g.ua(f),f5("Caption downloading error",e,b.cotn),g.qa(f)}})},C0a=function(a,b){var c,d,e,f,k;
return g.B(function(l){switch(l.j){case 1:return a.j=b,c=g.hC(a.j.key),"TRANSFER_STATE_TRANSFERRING"===a.j.transferState&&j5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,pj:a.j}),g.A(l,V5(a),2);case 2:return d=null,g.sa(l,3),g.A(l,F0a(a,b),5);case 5:d=l.u;a.B=d;g.ta(l,4);break;case 3:return e=g.ua(l),f5("error getting player response",e,b.cotn),g.A(l,a.Zr("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=
S_a(a.api.R(),b.cotn,d),g.A(l,E0a(a,f),7);case 7:return k=f,g.A(l,r0a(f.videoId),8);case 8:k.Tm=l.u;var m=a.I,n=b.maximumDownloadQuality;f.getPlayerResponse();g.uC(f.videoId,2);m.B=2;m.u=!1;var p;null==(p=m.player)||p.dispose();m.player=m.api.So(9,f);p={};g.Rt(m.player,(p.localmediachange=m.AC,p.signatureexpired=m.kI,p.statechange=m.FY,p),m);n=v0a(n);m.K("hoffle_lmqf_killswitch")||g.KNa(m.player,g.rw(n,n,!0,"m"),!1);g.pN(m.player,!1);W5(a);g.qa(l)}})},B0a=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,c5(a.u,"transfer"),2);b=d.u;c=b.filter(G0a).sort(H0a);return 0===c.length?d.return():d.return(c[0])})},V5=function(a){return g.B(function(b){W5(a);
return g.A(b,X5(a,"TRANSFER_STATE_TRANSFERRING"),0)})},t0a=function(a){var b;
g.B(function(c){if(1==c.j)return a.C.stop(),g.A(c,X5(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.hC(a.j.key);x_a({videoId:b.entityId,pj:a.j});T5(a);U5(a);g.qa(c)})},u0a=function(a){g.B(function(b){if(1==b.j)return a.C.stop(),g.A(b,X5(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
T5(a);g.qa(b)})},I0a=function(a){var b,c,d;
g.B(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.Oa(2);break}b=S_a(a.api.R(),a.j.cotn,a.B);return g.A(e,E0a(a,b),2);case 2:return g.A(e,X5(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.hC(a.j.key),d=c.entityId,g.A(e,z0a(a.u,d),5);case 5:j5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,pj:a.j}),T5(a),U5(a),g.qa(e)}})},K0a=function(a,b,c){var d;
g.B(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.Oa(2);break}return g.A(e,V5(a),2);case 2:d=Date.now();if(!(1E3<d-a.U)){e.Oa(4);break}a.U=d;return g.A(e,y0a(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:if(a.j.hasLoggedFirstStarted){w_a({videoId:b,pj:a.j},c.bytesDownloaded,c.j);e.Oa(4);break}a.j.hasLoggedFirstStarted=!0;return g.A(e,J0a(a),7);case 7:w_a({videoId:b,pj:a.j},c.bytesDownloaded,c.j,!0);case 4:W5(a),g.qa(e)}})},L0a=function(a){var b=
3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},M0a=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.B(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.A(e,X5(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);h5(a.ma,{entityKey:a.j.key,failureReason:c});d=g.hC(a.j.key).entityId;var f={videoId:d,pj:a.j},k=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};k&&(l.transferFailureReason=k,l.failureReason=y_a(k));j5(l,f);g.qa(e)})},X5=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.sa(f,2),g.A(f,J0a(a,function(k){return c?R4(k,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.r(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.r(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return U4(k,l.filter(function(q){return!!q}),"offlineVideoStreams")}):g.pr.resolve(void 0)}),4);
if(2!=f.j)return g.ta(f,0);e=g.ua(f);return e instanceof g.ir&&"QUOTA_EXCEEDED"===e.type?g.A(f,a.Zr("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.Oa(0)})},J0a=function(a,b){var c;
return g.B(function(d){if(!a.j)return d.return();c=a.j;return g.A(d,Z4(a.u,{mode:"readwrite",jc:!0},function(e){var f=[T4(e,c,"transfer")];b&&f.push(b(e));return g.pr.all(f)}),0)})},T5=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},F0a=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.hC(b.key),d=c.entityId,e=g.iC(d,"playbackData"),g.A(l,b5(a.u,e,"playbackData"),2);f=l.u;if(null==(k=f)?0:k.playerResponseJson)return l.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},W5=function(a){a.C.start(a.Ca||18E5)},G0a=function(a){return void 0!==Y5[a.transferState]},H0a=function(a,b){var c=Y5[a.transferState],d=Y5[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},Z5=function(a,b){var c=this;
this.environmentData=a;this.api=b;this.P=new g.ts;this.B=new r_a(function(){return N0a(c)},function(){O0a(c)},this.api.wp(),this.api.K.bind(this.api));
this.u=new g5(this.api);this.C=new g.Rh;s_a(this.B)},N0a=function(a){return g.B(function(b){a.api.Ia("onOrchestrationBecameLeader");
a.j&&a.D||P0a(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.A(b,c,0)})},P0a=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return g.A(e,e5(),2);if(3!=e.j){b=e.u;if(!b)return f5("PES is undefined"),e.return();a.j=new S5(b,a.api,a.B,a.u);c=a.Lx(b);d=a;return g.A(e,c0a(b,c,a.B,a.u),3)}d.D=e.u;return g.A(e,Q0a(a),0)})},Q0a=function(a){var b;
return g.B(function(c){switch(c.j){case 1:if(!a.j)return f5("transferManager is undefined"),c.return();if(a.j.j){c.Oa(2);break}return g.A(c,U5(a.j),2);case 2:return g.A(c,a.pz(),4);case 4:return a.J=g.Pp(function(){a.pz()},9E5),g.Nq(g.Pq(),function(){return a.dJ()}),g.A(c,e5(),5);
case 5:return b=c.u,g.A(c,n_a(b),6);case 6:t_a(a.B),g.qa(c)}})},O0a=function(a){var b,c;
g.B(function(d){if(1==d.j)return a.j||a.D?g.A(d,a.C.promise,2):d.return();void 0!==a.J&&(window.clearInterval(a.J),a.J=void 0);null==(b=a.j)||b.dispose();a.j=void 0;null==(c=a.D)||c.dispose();a.D=void 0;a.api.Ia("onOrchestrationLostLeader");a.C=new g.Rh;g.qa(d)})},R0a=function(){var a,b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return g.A(k,e5(),2);case 2:a=k.u;if(!a)return k.return([]);b=Date.now()/1E3;return g.A(k,c5(a,"offlineVideoPolicy"),3);case 3:c=k.u,d=g.r(c),e=d.next();case 4:if(e.done){k.Oa(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){k.Oa(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.A(k,a5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();k.Oa(4);break;case 6:return k.return(c.map(function(l){return l.key}))}})},$5=
function(a,b,c,d,e){var f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,e5(),2);f=m.u;if(!f)return m.return([]);k=b.map(function(n){var p=g.iC(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign({},T_a(),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new H5(c,n,p);return I5(n)});
l=YZa(f,k);s_a(a.B);return m.return(l)})},a6=function(a){var b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return b=g.HH(),c=k_a(a),d=g.sH(S0a),g.sa(k,2),g.A(k,g.DF(b,c,d),4);case 4:e=k.u;g.ta(k,3);break;case 2:throw f=g.ua(k),f5("GetOffline fetch request error",f),Error("GetOffline fetch request error");case 3:if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return k.return(e.videos.map(function(l){return l.offlineVideoData}))}})},T0a=function(a){var b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return b=g.HH(),c=l_a(a),d=g.sH(S0a),g.sa(k,2),g.A(k,g.DF(b,c,d),4);case 4:e=k.u;g.ta(k,3);break;case 2:throw f=g.ua(k),f5("GetOffline fetch request error for playlist",f),Error("GetOffline fetch request error for playlist");case 3:if(!e)throw Error("Network request failed");if(!e.playlists||!e.playlists.length)throw Error("No data");return k.return(e.playlists.map(function(l){return l.offlinePlaylistData}))}})},V0a=function(){var a,b,c,d,e;
return g.B(function(f){switch(f.j){case 1:return a=g.HH(),b={context:g.xF(),browseId:"FEdownloads",browseRequestSupportedMetadata:{downloadsBrowseParams:{offlineFeatureSettingState:{isSdEnabled:!1}}}},c=g.sH(U0a),g.sa(f,2),g.A(f,g.DF(a,b,c),4);case 4:d=f.u;g.ta(f,3);break;case 2:throw e=g.ua(f),f5("DPS fetch request error for smart downloads",e),Error("DPS fetch request error for smart downloads");case 3:if(!d)throw Error("Network request failed");return f.return(d)}})},b6=function(a,b){this.j=a;
this.B=b},X0a=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u,x;
return g.B(function(y){switch(y.j){case 1:return c=t5(b),d=g.hC(b.entityKey),e=d.entityId,f=[],g.sa(y,2),g.A(y,W0a(a,e),4);case 4:f=y.u;g.ta(y,3);break;case 2:return k=g.ua(y),l="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",k instanceof g.ir&&"QUOTA_EXCEEDED"===k.type&&(l="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),y.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,l));case 3:m=[];if(null==(n=f)?0:n.length)for(p=g.r(f),q=p.next();!q.done;q=p.next())t=q.value,u=t.offlineVideoData,
x=void 0,(null==(x=u)?0:x.videoId)&&m.push(c6("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",u.videoId,d6(b,u)));return y.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m))}})},Y0a=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u,x,y,z,D,G,H,L,aa,M,ha,ra,X,oa,Ja,Sa,Za,eb,Vb,Wb,fc,Na,jc,Vd,Qe,Af,zg,re,Zb,Ag,Re,kj;
return g.B(function(Md){switch(Md.j){case 1:return c=t5(b),d=b.entityKey,e=g.hC(d).entityId,g.A(Md,b5(a.j,d,"mainPlaylistEntity"),2);case 2:f=Md.u;if(!f)return Md.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));k=[];l=new Map;m=[];g.sa(Md,3);return g.A(Md,W0a(a,e),5);case 5:k=Md.u;g.ta(Md,4);break;case 3:return n=g.ua(Md),n instanceof Error&&"No data"===n.message?g.A(Md,E_a(e,a.j,b,a.B),4):(p="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",n instanceof g.ir&&"QUOTA_EXCEEDED"===n.type&&
(p="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),Md.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,p)));case 4:q=[];t=new Map;if(null==(u=k)?0:u.length)for(x=g.r(k),y=x.next();!y.done;y=x.next())z=y.value,D=z.offlineVideoData,G=void 0,(null==(G=D)?0:G.videoId)&&t.set(D.videoId,D);if(null==(H=f)?0:null==(L=H.videos)?0:L.length)for(aa=g.r(f.videos),M=aa.next();!M.done;M=aa.next())if(ha=M.value,ra=JSON.parse(g.hC(ha).entityId),X=ra.videoId)t.has(X)?(l.set(X,t.get(X)),
t.delete(X)):m.push(X);oa=g.r(t.entries());for(Ja=oa.next();!Ja.done;Ja=oa.next())Sa=Ja.value,Za=g.r(Sa),eb=Za.next().value,Vb=Za.next().value,Wb=eb,fc=Vb,q.push(c6("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",Wb,d6(b,fc)));Na=g.r(l.entries());for(jc=Na.next();!jc.done;jc=Na.next())Vd=jc.value,Qe=g.r(Vd),Af=Qe.next().value,zg=Qe.next().value,re=Af,Zb=zg,q.push(c6("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",re,d6(b,Zb)));Ag=g.r(m);for(Re=Ag.next();!Re.done;Re=Ag.next())kj=Re.value,q.push(c6("OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE",
kj));return Md.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,q))}})},Z0a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.sa(e,2),d=g.hC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,B5(a.j,b,a.B),5):g.A(e,E_a(d,a.j,b,a.B),5);case 5:g.ta(e,3);break;case 2:return g.ua(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},W0a=function(a,b){var c,d,e,f,k;
return g.B(function(l){switch(l.j){case 1:return g.A(l,T0a([b]),2);case 2:return c=l.u,g.A(l,$0a(a,c[0]),3);case 3:return d=l.u,e=d.mainPlaylistEntity,f=d.S_,k=C_a(e,f.avatar),g.A(l,s5(k),4);case 4:return l.return(c[0].videos)}})},$0a=function(a,b){var c=void 0,d,e,f,k,l,m,n,p,q,t,u,x,y,z;
return g.B(function(D){if(1==D.j){if(!(b&&b.playlistId&&b.channel&&b.channel.offlineChannelData))throw Error("Invalid OfflinePlaylistData");c||(c=Date.now().toString());d=b.videos;e=b.playlistId;f=[];k=[];if(d)for(l=g.r(d),m=l.next();!m.done;m=l.next()){n=m.value;p=n.offlineVideoData;if(!p||!p.videoId)throw Error("Invalid offlineVideoData");q=p.videoId;t={videoId:q,playlistId:e};u={id:g.iC(JSON.stringify(t),"mainPlaylistVideoEntity"),video:g.iC(q,"mainVideoEntity")};f.push(u);k.push(u.id)}x=b.channel.offlineChannelData;
y=a1a(g.iC(e,"ytMainChannelEntity"),x);z={key:g.iC(e,"mainPlaylistEntity"),playlistId:e,channelOwner:y.id,videos:k,title:b.title,thumbnailStyleData:b1a(b),visibility:c1a(b)};return g.A(D,Z4(a.j,{mode:"readwrite",jc:!0},function(G){for(var H=T4(G,z,"mainPlaylistEntity"),L=T4(G,y,"ytMainChannelEntity"),aa=[],M=g.r(f),ha=M.next();!ha.done;ha=M.next())aa.push(T4(G,ha.value,"mainPlaylistVideoEntity"));return g.pr.all([H,L].concat(g.v(aa)))}),2)}return D.return({mainPlaylistEntity:z,
S_:y,Kka:f})})},c6=function(a,b,c){b=g.iC(b,"mainVideoEntity");
c=Object.assign({},c,{priority:0,retryScheduleIntervalsInSeconds:d1a});return{actionType:a,entityKey:b,actionMetadata:c}},a1a=function(a,b){if(!(b.channelId&&b.title&&b.thumbnail))throw Error("Invalid OfflineChannelData");
return{id:a,channelId:b.channelId,title:b.title,avatar:b.thumbnail}},b1a=function(a){var b=[],c=a.videos;
c&&0<c.length&&b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_FIRST_VIDEO"),value:{collageThumbnail:{coverThumbnail:c[0].offlineVideoData.thumbnail}}});if((a=a.additionalMetadadatas)&&0<a.length)for(a=g.r(a),c=a.next();!c.done;c=a.next()){var d=c.value.offlineBundleItemPlaylistData,e=void 0;c=null==(e=d)?void 0:e.style;e=void 0;d={collageThumbnail:{coverThumbnail:null==(e=d)?void 0:e.coverThumbnail}};switch(c){case "BUNDLE_ITEM_STYLE_UNSPECIFIED":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_UNKNOWN"),
value:d});break;case "BUNDLE_ITEM_STYLE_TWO_BY_TWO":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_TWO_BY_TWO"),value:d});break;case "BUNDLE_ITEM_STYLE_ONE_AND_TWO_AVATAR":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_ONE_AND_TWO_AVATAR"),value:d});break;case "BUNDLE_ITEM_STYLE_ONE_AND_TWO":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_ONE_AND_TWO"),value:d})}}return b},c1a=function(a){switch(a.privacy){case "PRIVATE":return"PLAYLIST_VISIBILITY_PRIVATE";
case "PUBLIC":return"PLAYLIST_VISIBILITY_PUBLIC";case "UNLISTED":return"PLAYLIST_VISIBILITY_UNLISTED";default:return"PLAYLIST_VISIBILITY_UNKNOWN"}},d6=function(a,b){b={offlineVideoData:b};
var c;if(null==(c=a.actionMetadata)?0:c.mainPlaylistEntityActionMetadata)b.maximumDownloadQuality=a.actionMetadata.mainPlaylistEntityActionMetadata.maximumDownloadQuality;return{mainVideoEntityActionMetadata:b}},e6=function(a,b){this.j=a;
this.B=b},g1a=function(a,b){var c,d,e,f,k,l,m,n;
return g.B(function(p){switch(p.j){case 1:return c=t5(b),d=g.hC(b.entityKey),e=d.entityId,g.sa(p,2),g.A(p,e1a(a,e,void 0,null==(f=b.actionMetadata)?void 0:null==(k=f.mainVideoEntityActionMetadata)?void 0:k.offlineVideoData),4);case 4:g.ta(p,3);break;case 2:return l=g.ua(p),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.ir&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),p.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m));
case 3:var q;var t=null!=(q=b.actionMetadata)&&q.mainVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.mainVideoEntityActionMetadata.maximumDownloadQuality}}:void 0;n=f1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,t);return p.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[n]))}})},h1a=function(a,b){var c,d,e,f,k,l,m,n,p,q,t;
return g.B(function(u){switch(u.j){case 1:return c=t5(b),d=g.hC(b.entityKey),e=d.entityId,g.A(u,b5(a.j,b.entityKey,"mainVideoEntity"),2);case 2:f=u.u;if(!f){k=void 0;u.Oa(3);break}return g.A(u,b5(a.j,f.downloadState,"mainVideoDownloadStateEntity"),4);case 4:k=u.u;case 3:l=k;if(!f||!l)return u.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.sa(u,5);return g.A(u,e1a(a,e,l.addedTimestampMillis,null==(n=b.actionMetadata)?void 0:null==(p=n.mainVideoEntityActionMetadata)?void 0:p.offlineVideoData),
7);case 7:m=f1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.ta(u,6);break;case 5:return q=g.ua(u),q instanceof Error&&"No data"===q.message?g.A(u,A5(e,a.j,b,a.B),6):(t="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",q instanceof g.ir&&"QUOTA_EXCEEDED"===q.type&&(t="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),u.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,t)));case 6:return u.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m?[m]:void 0))}})},i1a=
function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.sa(e,2),d=g.hC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,B5(a.j,b,a.B),5):g.A(e,A5(d,a.j,b,a.B),5);case 5:g.ta(e,3);break;case 2:return g.ua(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},e1a=function(a,b,c,d){var e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:if(e=d){n.Oa(2);break}return g.A(n,a6([b]),3);case 3:f=n.u,e=f[0];case 2:return g.A(n,j1a(a,e,c),4);case 4:k=n.u;l=k.mainVideoEntity;m=k.channelEntity;var p=x5(l.thumbnail),q=x5(m.avatar);return g.A(n,s5(p.concat(q)),0)}})},j1a=function(a,b,c){var d,e,f,k,l;
return g.B(function(m){if(1==m.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.iC(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};k={key:g.iC(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.iC(b.videoId,"playbackData"),addedTimestampMillis:c};l={key:g.iC(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,
thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:k.key};return g.A(m,Z4(a.j,{mode:"readwrite",jc:!0},function(n){var p=T4(n,f,"ytMainChannelEntity"),q=T4(n,k,"mainVideoDownloadStateEntity");n=T4(n,l,"mainVideoEntity");return g.pr.all([p,q,n])}),2)}return m.return({mainVideoEntity:l,
channelEntity:f})})},f1a=function(a,b,c){b=g.iC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:k1a});return{actionType:a,entityKey:b,actionMetadata:c}},f6=function(a,b){this.j=a;
this.environmentData=b},m1a=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u,x,y;
return g.B(function(z){switch(z.j){case 1:c=t5(b);d=[];if(!a.environmentData.K("kevlar_smart_downloads")){z.Oa(2);break}g.sa(z,3);return g.A(z,V0a(),5);case 5:return e=z.u,g.A(z,l1a(e),6);case 6:var D;a:{var G;if(null!=(G=e.onResponseReceivedActions)&&G.length){var H;G=null==(D=e.onResponseReceivedActions[0].elementsCommand)?void 0:null==(H=D.offlineOrchestrationActionCommand)?void 0:H.actions;if(null!=G&&G.length){D=G;break a}}D=void 0}f=D;if(null==(k=f)?0:k.length)for(l=g.r(f),m=l.next();!m.done;m=
l.next())p=n=m.value,q=p.actionType,t=p.entityKey,u=p.actionMetadata,q&&t&&u&&!u.localImageEntityActionMetadata&&d.push(n);g.ta(z,2);break;case 3:return x=g.ua(z),y="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",x instanceof g.ir&&"QUOTA_EXCEEDED"===x.type&&(y="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),z.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,y));case 2:return z.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,d))}})},l1a=function(a){return g.B(function(b){return a.frameworkUpdates&&
a.frameworkUpdates.entityBatchUpdate?g.A(b,c_a(a.frameworkUpdates.entityBatchUpdate),0):b.return()})},g6=function(a,b,c){this.j=a;
this.environmentData=b;this.B=c},p1a=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return c=t5(b),d=g.hC(b.entityKey),e=d.entityId,g.sa(m,2),g.A(m,n1a(a,e),4);case 4:g.ta(m,3);break;case 2:return f=g.ua(m),k="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.ir&&"QUOTA_EXCEEDED"===f.type&&(k="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,k));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=o1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},q1a=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return c=t5(b),d=g.hC(b.entityKey),e=d.entityId,g.A(n,b5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.sa(n,3);return g.A(n,n1a(a,e,f.addedTimestampMillis),5);case 5:k=o1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.ta(n,4);break;case 3:return l=g.ua(n),l instanceof Error&&"No data"===l.message?g.A(n,A5(e,a.j,b,a.B),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.ir&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,k?[k]:void 0))}})},r1a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.sa(e,2),d=g.hC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,B5(a.j,b,a.B),5):g.A(e,A5(d,a.j,b,a.B),5);case 5:g.ta(e,3);break;case 2:return g.ua(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},n1a=function(a,b,c){var d,e,f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,a6([b]),2);if(3!=m.j)return d=m.u,e=d[0],g.A(m,s1a(a,e,c),3);f=m.u;k=f.videoEntity;l=f.channelEntity;var n=x5(k.thumbnail),p=x5(l.avatar);return g.A(m,s5(n.concat(p)),0)})},s1a=function(a,b,c){var d,e,f,k,l,m,n;
return g.B(function(p){if(1==p.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.iC(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};k={id:g.iC(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):
void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.iC(b.videoId,"ytMainDownloadedVideoEntity"),video:k.id,playbackData:g.iC(b.videoId,"playbackData"),offlineVideoPolicy:g.iC(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return a.environmentData.K("woffle_entity_migration")?(m={key:g.iC(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.iC(b.videoId,"playbackData"),addedTimestampMillis:c},
n={key:g.iC(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:m.key},g.A(p,Z4(a.j,{mode:"readwrite",jc:!0},function(q){var t=T4(q,f,"ytMainChannelEntity"),u=T4(q,k,"ytMainVideoEntity"),x=T4(q,l,"ytMainDownloadedVideoEntity"),
y=T4(q,m,"mainVideoDownloadStateEntity");q=T4(q,n,"mainVideoEntity");return g.pr.all([t,u,x,y,q])}),3)):g.A(p,Z4(a.j,{mode:"readwrite",
jc:!0},function(q){var t=T4(q,f,"ytMainChannelEntity"),u=T4(q,k,"ytMainVideoEntity");q=T4(q,l,"ytMainDownloadedVideoEntity");return g.pr.all([t,u,q])}),3)}return p.return({videoEntity:k,
channelEntity:f,Yja:l})})},o1a=function(a,b,c){b=g.iC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:t1a});return{actionType:a,entityKey:b,actionMetadata:c}},h6=function(){Z5.apply(this,arguments);
this.I="ytMainDownloadedVideoEntity"},u1a=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,e5(),2):(a=b.u)?g.A(b,Z4(a,{mode:"readwrite",jc:!0},function(c){var d=R4(c,"ytMainDownloadedVideoEntity"),e=R4(c,"ytMainVideoEntity"),f=R4(c,"mainVideoEntity");return g.pr.all([d,e,f]).then(function(k){k=g.r(k);var l=k.next().value,m=k.next().value,n=k.next().value;k={};l=g.r(l);for(var p=l.next();!p.done;p=l.next()){p=p.value;var q=g.hC(p.id).entityId;k[q]=p}l={};m=g.r(m);for(p=m.next();!p.done;p=m.next())p=p.value,q=g.hC(p.id).entityId,l[q]=p;m={};n=g.r(n);
for(p=n.next();!p.done;p=n.next())p=p.value,q=g.hC(p.key).entityId,m[q]=p;n=[];p=g.r(Object.keys(k));for(q=p.next();!q.done;q=p.next())if(q=q.value,!m[q]&&l[q]){var t=k[q],u=l[q];t={key:g.iC(q,"mainVideoDownloadStateEntity"),playbackData:g.iC(q,"playbackData"),addedTimestampMillis:t.addedTimestampMillis};q=[{key:g.iC(q,"mainVideoEntity"),videoId:q,title:u.title,thumbnail:u.thumbnail,localizedStrings:u.localizedStrings,lengthSeconds:u.lengthSeconds,publishedTimestampMillis:u.publishedTimestampMillis,
formattedDescription:u.formattedDescription,owner:u.channelOwner,downloadState:t.key},t];n.push(T4(c,q[0],"mainVideoEntity"),T4(c,q[1],"mainVideoDownloadStateEntity"))}return g.pr.all(n)})}),0):b.return()})},i6=function(a,b){this.j=a;
this.B=b},x1a=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return c=t5(b),d=g.hC(b.entityKey),e=d.entityId,g.sa(m,2),g.A(m,v1a(a,e),4);case 4:g.ta(m,3);break;case 2:return f=g.ua(m),k="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.ir&&"QUOTA_EXCEEDED"===f.type&&(k="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,k));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.musicTrackEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.musicTrackEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=w1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},y1a=function(a,b){var c,d,e,f,k,l,m,n,p;
return g.B(function(q){switch(q.j){case 1:return c=t5(b),d=g.hC(b.entityKey),e=d.entityId,g.A(q,b5(a.j,b.entityKey,"musicTrack"),2);case 2:f=q.u;if(!f){k=void 0;q.Oa(3);break}return g.A(q,b5(a.j,f.downloadMetadata,"musicTrackDownloadMetadataEntity"),4);case 4:k=q.u;case 3:l=k;if(!f||!l)return q.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.sa(q,5);return g.A(q,v1a(a,e,l.addedTimestampMillis),7);case 7:m=w1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.ta(q,6);break;case 5:return n=
g.ua(q),n instanceof Error&&"No data"===n.message?g.A(q,H_a(e,a.j,b,a.B),6):(p="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",n instanceof g.ir&&"QUOTA_EXCEEDED"===n.type&&(p="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),q.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,p)));case 6:return q.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m?[m]:void 0))}})},z1a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.sa(e,2),d=g.hC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,I_a(a.j,b,a.B),5):g.A(e,H_a(d,a.j,b,a.B),5);case 5:g.ta(e,3);break;case 2:return g.ua(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},v1a=function(a,b,c){var d,e,f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,a6([b]),2);if(3!=m.j)return d=m.u,e=d[0],g.A(m,A1a(a,e,c),3);f=m.u;k=f.musicTrackEntity;l=f.musicArtistEntity;var n=x5(k.thumbnailDetails),p=x5(l.thumbnailDetails);return g.A(m,s5(n.concat(p)),0)})},A1a=function(a,b,c){var d,e,f,k,l,m,n,p,q,t,u,x,y,z;
return g.B(function(D){if(1==D.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId&&b.additionalMetadatas))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=g.r(b.additionalMetadatas);for(f=e.next();!f.done;f=e.next())k=f.value,k.offlineMusicVideoData&&(d=k.offlineMusicVideoData);if(!d)throw Error("Invalid OfflineMusicVideoData");m=null==(l=b.channel)?void 0:l.offlineChannelData;n={id:g.iC(b.videoId,"musicArtist"),externalChannelId:m.channelId,name:m.title,thumbnailDetails:m.thumbnail};
p={id:g.iC(b.videoId,"musicTrackDownloadMetadataEntity"),playbackData:g.iC(b.videoId,"playbackData"),addedTimestampMillis:c};z={id:g.iC(b.videoId,"musicTrack"),videoId:b.videoId,title:b.title,thumbnailDetails:b.thumbnail,lengthMs:String(1E3*Number(b.lengthSeconds)),albumTitle:null==(q=d)?void 0:q.releaseTitle,musicVideoType:null==(t=d)?void 0:t.musicVideoType,contentRating:{explicitType:null==(u=d)?void 0:u.explicitType},artists:[n.id],artistNames:(null==(x=d)?void 0:x.byline)||(null==(y=d)?void 0:
y.channelName),downloadMetadata:p.id};return g.A(D,Z4(a.j,{mode:"readwrite",jc:!0},function(G){var H=T4(G,n,"musicArtist"),L=T4(G,p,"musicTrackDownloadMetadataEntity");G=T4(G,z,"musicTrack");return g.pr.all([H,L,G])}),2)}return D.return({musicTrackEntity:z,
musicArtistEntity:n})})},w1a=function(a,b,c){b=g.iC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:B1a});return{actionType:a,entityKey:b,actionMetadata:c}},j6=function(){Z5.apply(this,arguments);
this.I="musicTrack"},k6=function(){g.EI.apply(this,arguments)};
g.w(J3,I3);g.da.Object.defineProperties(J3.prototype,{entityMetadata:{configurable:!0,enumerable:!0,get:function(){return this.j.entityMetadata},
set:function(a){this.j.entityMetadata=a}}});
g.w(K3,J3);K3.prototype.u=function(){return[]};
g.w(L3,J3);L3.prototype.u=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.v(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.v(new Set(a)))};
g.w(M3,J3);M3.prototype.u=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.v(new Set(a)))};
g.w(N3,I3);N3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.v(new Set(a)))};
g.w(O3,J3);O3.prototype.u=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.r(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.v((new N3(c.value)).u()));return[].concat(g.v(new Set(a)))};
g.w(P3,J3);P3.prototype.u=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.v(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.v(new Set(a)))};
g.w(Q3,J3);Q3.prototype.u=function(){return[]};
g.w(R3,J3);R3.prototype.u=function(){return[]};
g.w(S3,J3);S3.prototype.u=function(){return[]};
g.w(T3,J3);T3.prototype.u=function(){return[]};
g.w(U3,J3);U3.prototype.u=function(){return[]};
g.w(V3,I3);V3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playlist&&a.push(this.j.playlist);this.j.videoItem&&a.push(this.j.videoItem);return[].concat(g.v(new Set(a)))};
g.w(W3,J3);W3.prototype.u=function(){var a=[];this.j.refresh&&a.push(this.j.refresh);if(this.j.downloads)for(var b=g.r(this.j.downloads),c=b.next();!c.done;c=b.next())a.push.apply(a,g.v((new V3(c.value)).u()));return[].concat(g.v(new Set(a)))};
g.w(X3,J3);X3.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));return[].concat(g.v(new Set(a)))};
g.w(Y3,J3);Y3.prototype.u=function(){return[]};
g.w(Z3,J3);Z3.prototype.u=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.v(this.j.fakeChildren));return[].concat(g.v(new Set(a)))};
g.w($3,J3);$3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.v(new Set(a)))};
g.w(a4,J3);a4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.videos&&a.push.apply(a,g.v(this.j.videos));this.j.collaboratorChannels&&a.push.apply(a,g.v(this.j.collaboratorChannels));this.j.downloadState&&a.push(this.j.downloadState);return[].concat(g.v(new Set(a)))};
g.w(b4,J3);b4.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.channelContributor&&a.push(this.j.channelContributor);return[].concat(g.v(new Set(a)))};
g.w(c4,I3);c4.prototype.u=function(){var a=[];this.j.playbackPosition&&a.push(this.j.playbackPosition);return[].concat(g.v(new Set(a)))};
g.w(d4,J3);d4.prototype.u=function(){var a=[];this.j.owner&&a.push(this.j.owner);this.j.downloadState&&a.push(this.j.downloadState);this.j.userState&&a.push.apply(a,g.v((new c4(this.j.userState)).u()));return[].concat(g.v(new Set(a)))};
g.w(e4,J3);e4.prototype.u=function(){return[]};
g.w(f4,J3);f4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.v(new Set(a)))};
g.w(g4,J3);g4.prototype.u=function(){return[]};
g.w(h4,J3);h4.prototype.u=function(){return[]};
g.w(i4,J3);i4.prototype.u=function(){return[]};
g.w(j4,J3);j4.prototype.u=function(){var a=[];this.j.trackDownloadMetadatas&&a.push.apply(a,g.v(this.j.trackDownloadMetadatas));return[].concat(g.v(new Set(a)))};
g.w(k4,J3);k4.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));return[].concat(g.v(new Set(a)))};
g.w(l4,J3);l4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.primaryArtists&&a.push.apply(a,g.v(this.j.primaryArtists));this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);this.j.tracks&&a.push.apply(a,g.v(this.j.tracks));this.j.share&&a.push(this.j.share);this.j.downloadMetadata&&a.push(this.j.downloadMetadata);return[].concat(g.v(new Set(a)))};
g.w(m4,J3);m4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);this.j.tracks&&a.push.apply(a,g.v(this.j.tracks));return[].concat(g.v(new Set(a)))};
g.w(n4,J3);n4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);return[].concat(g.v(new Set(a)))};
g.w(o4,J3);o4.prototype.u=function(){var a=[];this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);return[].concat(g.v(new Set(a)))};
g.w(p4,J3);p4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.v(new Set(a)))};
g.w(q4,J3);q4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.v(new Set(a)))};
g.w(r4,J3);r4.prototype.u=function(){return[]};
g.w(s4,J3);s4.prototype.u=function(){return[]};
g.w(t4,J3);t4.prototype.u=function(){return[]};
g.w(u4,J3);
u4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.artists&&a.push.apply(a,g.v(this.j.artists));this.j.audioModeVersion&&a.push(this.j.audioModeVersion);this.j.videoModeVersion&&a.push(this.j.videoModeVersion);this.j.userDetails&&a.push(this.j.userDetails);this.j.details&&a.push(this.j.details);this.j.albumRelease&&a.push(this.j.albumRelease);this.j.share&&a.push(this.j.share);this.j.libraryEdit&&a.push(this.j.libraryEdit);this.j.downloadMetadata&&
a.push(this.j.downloadMetadata);return[].concat(g.v(new Set(a)))};
g.w(v4,J3);v4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.v(new Set(a)))};
g.w(w4,J3);w4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.v(new Set(a)))};
g.w(x4,J3);x4.prototype.u=function(){return[]};
g.w(y4,J3);y4.prototype.u=function(){return[]};
g.w(z4,J3);z4.prototype.u=function(){return[]};
g.w(A4,J3);A4.prototype.u=function(){return[]};
g.w(B4,J3);B4.prototype.u=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.v(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.v(new Set(a)))};
g.w(C4,J3);C4.prototype.u=function(){return[]};
g.w(D4,J3);D4.prototype.u=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.v(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.v(this.j.captionTrack));return[].concat(g.v(new Set(a)))};
g.w(E4,J3);E4.prototype.u=function(){return[]};
g.w(F4,J3);F4.prototype.u=function(){return[]};
g.w(G4,J3);G4.prototype.u=function(){return[]};
g.w(H4,J3);H4.prototype.u=function(){return[]};
g.w(I4,J3);I4.prototype.u=function(){return[]};
var U0a=["browse","music/browse","unplugged/browse"],S0a=["offline"],O_a=["offline/get_playback_data_entity"],K4;g.w(L4,g.dr);g.w(N4,MZa);N4.prototype.B=function(a,b){b=M4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
N4.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw IZa(1);var c=new TextDecoder;b=M4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
var OZa={buttonEntity:E4,captionTrack:x4,channelHandle:K3,commerceCartListEntity:G4,downloadQualityPickerEntity:T3,downloadsPageRefreshTokenEntity:U3,downloadsPageViewConfigurationEntity:g4,fakeChannel:L3,fakePlaylist:M3,fakePlaylistEntryCollection:O3,fakeVideo:P3,fakeVideoDescription:Q3,iconBadgeEntity:H4,liveChatPollStateEntity:S3,logoEntity:R3,mainDownloadsListEntity:W3,mainPlaylistEntity:a4,mainPlaylistVideoEntity:b4,mainVideoDownloadStateEntity:X3,mainVideoEntity:d4,markersVisibilityOverrideEntity:h4,
musicAlbumReleaseDetail:m4,musicAlbumReleaseDownloadMetadataEntity:j4,musicAlbumRelease:l4,musicAlbumReleaseUserDetail:n4,musicArtistDetail:p4,musicArtist:o4,musicArtistUserDetail:q4,musicLibraryEdit:r4,musicLibraryStatusEntity:s4,musicShare:t4,musicTrackDetail:v4,musicTrackDownloadMetadataEntity:k4,musicTrack:u4,musicTrackUserDetail:w4,offlineOrchestrationActionWrapperEntity:y4,offlineVideoPolicy:z4,offlineVideoStreams:A4,offlineabilityEntity:Y3,orchestrationWebSamplingEntity:Z3,pinnedProductEntity:i4,
playbackData:B4,quantityIncrementerEntity:I4,refresh:C4,transfer:D4,videoPlaybackPositionEntity:F4,ytMainChannelEntity:e4,ytMainDownloadedVideoEntity:$3,ytMainVideoEntity:f4};QZa.prototype.updateEntity=function(a,b,c,d){var e=this,f=O4(this.u,1);return Q4(this,a,c).then(function(k){if(k){k=g.AB(k,b,d);var l={key:a,entityType:c,data:NZa(f,k,a),version:1};return g.pr.all([g.yr(e.j.objectStore("EntityStore"),l),RZa(e,k,c)])}}).then(function(){S4(e,a,c);
return a})};
g.w(X4,MZa);X4.prototype.B=function(a){return a};
X4.prototype.u=function(a){if(a instanceof Uint8Array)throw IZa(0);return a};
g.w(Y4,g.I);Y4.prototype.u=function(a){XZa(this,a.data)};
Y4.prototype.Y=function(){this.channel.close()};
var d5,C1a={x3:"captionTrack",i7:"ytMainDownloadedVideoEntity",j7:"ytMainVideoEntity",baa:"ytMainChannelEntity",caa:"mainPlaylistEntity",daa:"mainPlaylistVideoEntity",eaa:"mainVideoEntity",faa:"mainVideoDownloadStateEntity",qca:"musicAlbumReleaseDetail",rca:"musicAlbumReleaseDownloadMetadataEntity",sca:"musicAlbumRelease",tca:"musicAlbumReleaseUserDetail",uca:"musicArtistDetail",vca:"musicArtist",xca:"musicArtistUserDetail",Gca:"musicLibraryEdit",Hca:"musicLibraryStatusEntity",Rca:"musicShare",Wca:"musicTrackDetail",
Xca:"musicTrackDownloadMetadataEntity",Yca:"musicTrack",Zca:"musicTrackUserDetail",sda:"offlineOrchestrationActionWrapperEntity",Cda:"offlineVideoPolicy",Dda:"offlineVideoStreams",pea:"playbackData",tfa:"orchestrationWebSamplingEntity",Ega:"downloadsPageViewConfigurationEntity",Fga:"refresh",Gga:"mainDownloadsListEntity",Hga:"downloadsPageRefreshTokenEntity",wha:"transfer"};g.w(g5,g.I);g5.prototype.B=function(a){this.api.Ia("onOfflineOperationFailure",a.data)};
g5.prototype.C=function(a){this.api.W("offlinetransferpause",a.data)};
g5.prototype.Y=function(){var a;null==(a=this.j)||a.close();var b;null==(b=this.u)||b.close()};o_a.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};r_a.prototype.qf=function(){this.j&&i5(this)};var o5=g.C.caches,n5,p5;k5.prototype.open=function(a){return o5.open(m5(a))};
k5.prototype.has=function(a){return o5.has(m5(a))};
k5.prototype.delete=function(a){return o5.delete(m5(a))};
k5.prototype.match=function(a,b){var c=this,d,e,f,k,l,m;return g.B(function(n){switch(n.j){case 1:return g.A(n,c.keys(),2);case 2:d=n.u,e=g.r(d),f=e.next();case 3:if(f.done){n.Oa(5);break}k=f.value;return g.A(n,c.open(k),6);case 6:return l=n.u,g.A(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.Oa(3);break;case 5:return n.return()}})};
g.w(l5,k5);l5.prototype.keys=function(){var a,b,c,d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return a=[],b=g.er("CacheStorage keys"),g.A(n,o5.keys(),2);c=n.u;d=g.r(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");k=-1===p?{IC:f}:{IC:f.substring(0,p),datasyncId:f.substring(p+1)};l=k.IC;m=k.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(C1a).map(function(a){return C1a[a]});
var F_a="captionTrack ytMainDownloadedVideoEntity ytMainVideoEntity ytMainChannelEntity mainPlaylistEntity mainVideoEntity mainVideoDownloadStateEntity musicArtist musicTrack musicTrackDownloadMetadataEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.w(E5,C5);E5.prototype.u=function(a){return u5(a)?M_a(this,a):v5(a)?N_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(G5,C5);G5.prototype.u=function(a){return u5(a)?Q_a(this,a):v5(a)?R_a(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
G5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.B(function(f){switch(f.j){case 1:return c=t5(a),g.A(f,b5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.sa(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.A(f,a5(b.j,d,"transfer"),5);case 5:e=g.hC(d.key).entityId;j5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,pj:d});g.ta(f,4);break;case 3:return g.ua(f),f.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var g0a=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var J5;Z_a.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.w(M5,g.I);M5.prototype.Y=function(){this.J&&this.J();g.I.prototype.Y.call(this)};
M5.prototype.createAction=function(a,b){var c=g.hC(a.entityKey).entityType,d=g.nu(16);return new H5(c,d,a,b.actionId,b.rootActionId)};
M5.prototype.V=function(a){var b=this,c,d,e,f,k,l,m,n,p;return g.B(function(q){if(1==q.j){if(b.isDisposed())return q.return();d=null!=(c=a.offlineOrchestrationActionWrapperEntity)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.hC(l),n=m.entityId,a0a(b.j,n)||e.push(l);return g.A(q,i0a(b,e),2)}p=q.u;return g.A(q,O5(b,p),0)})};
M5.prototype.retry=function(){var a=this;return g.B(function(b){return g.A(b,j0a(a),0)})};g.h=p0a.prototype;g.h.FY=function(a){var b=this,c,d,e;return g.B(function(f){if(!g.U(a.state,128))return f.Oa(0);var k=null==(c=a.state.getData())?void 0:c.errorCode;a.state.getData();var l=null==(d=a.state.getData())?void 0:d.hB;e="net.connect"===k&&1===l?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null==k?0:k.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.A(f,b.Zr(b.player.getVideoData().videoId,e),0)})};
g.h.Zr=function(a,b){var c=this;return g.B(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(Q5(c,a,!1,!0),d.Oa(0)):g.A(d,P5(c,a),3)}g.uC(a,4);return g.A(d,c.j.Zr(b),0)})};
g.h.AC=function(a){2===a.status?(a.status!==this.B&&(V5(this.j),g.uC(a.videoId,2)),a.iz&&K0a(this.j,a.videoId,a.iz)):4===a.status?(P5(this,a.videoId),this.Zr(a.videoId,a.PB?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&I0a(this.j);this.B=a.status;this.api.Ia("localmediachange",{videoId:a.videoId,status:a.status})};
g.h.kI=function(){var a=this,b;return g.B(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.A(c,P5(a,b),2)}return g.A(c,a.j.kI(),0)})};
g.h.K=function(a){return this.api.R().K(a)};g.w(R5,g.I);R5.prototype.Y=function(){this.u&&this.u();g.I.prototype.Y.call(this)};
R5.prototype.B=function(a){var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){d=null!=(c=a.transfer)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.hC(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.A(p,w0a(b,e),0)})};g.w(S5,g.I);g.h=S5.prototype;g.h.Y=function(){this.J&&this.J();this.P.dispose();this.C.dispose();this.Z&&g.Fe(this.D.B,this.Z);this.V&&g.Fe(this.D.B,this.V);g.I.prototype.Y.call(this)};
g.h.O_=function(a){var b=this,c,d;return g.B(function(e){if(1==e.j)return c=g.iC(a,"transfer"),b.j&&c===b.j.key?(Q5(b.I,b.B,!0),b.C.stop(),e.Oa(0)):g.A(e,Z4(b.u,{mode:"readwrite",jc:!0},function(f){return Q4(f,c,"transfer").then(function(k){if(k&&"TRANSFER_STATE_COMPLETE"!==k.transferState&&"TRANSFER_STATE_FAILED"!==k.transferState)return k.transferState="TRANSFER_STATE_PAUSED_BY_USER",T4(f,k,"transfer").then(function(){return k})})}),3);
(d=e.u)&&x_a({videoId:a,pj:d});g.qa(e)})};
g.h.N_=function(){this.j&&this.B&&Q5(this.I,this.B,!1);this.C.stop()};
g.h.sz=function(){this.j?C0a(this,this.j):U5(this)};
g.h.SS=function(a){var b=this,c;return g.B(function(d){switch(d.j){case 1:if(!b.j){d.Oa(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.Oa(3);break}c=b;return g.A(d,b5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.Oa(3);break}return g.A(d,D0a(b),3);case 3:if(b.j)return d.return();case 2:return g.A(d,U5(b),0)}})};
g.h.Zr=function(a,b){var c=this,d,e;return g.B(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var k=!1;break a;default:k=!0}return k&&L0a(c)?g.A(f,X5(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.A(f,M0a(c,a),3)}3!=f.j&&(d=g.hC(c.j.key).entityId,j5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,pj:c.j}));T5(c);e=U5(c,!0);b&&b(e);g.qa(f)})};
g.h.kI=function(a){var b=this,c,d,e,f,k,l;return g.B(function(m){if(1==m.j)return L0a(b)?g.A(m,X5(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.A(m,M0a(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.hC(b.j.key).entityId,j5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,pj:b.j}),d=T_a(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.iC(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},k=I5(new H5("playbackData",c,f)),g.A(m,a5(b.u,k,"offlineOrchestrationActionWrapperEntity"),3);T5(b);l=U5(b,!0);a&&a(l);g.qa(m)})};
var l6={},Y5=(l6.TRANSFER_STATE_TRANSFERRING=1,l6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,l6);g.h=Z5.prototype;g.h.Lx=function(a){var b={};return b.playbackData=new E5(a,this.environmentData,this.u),b.transfer=new G5(a),b};
g.h.dJ=function(){var a=this;return g.B(function(b){return a.j?g.A(b,A0a(a.j),0):b.Oa(0)})};
g.h.isOrchestrationLeader=function(){return this.B.j};
g.h.BI=function(a){var b=this.u;b.api.W("offlinetransferpause",a);var c;null==(c=b.u)||c.postMessage(a)};
g.h.sz=function(a){var b,c;return g.B(function(d){if(1==d.j)return g.A(d,e5(),2);b=d.u;if(!b)return d.return();c=g.iC(a,"transfer");return g.A(d,Z4(b,{mode:"readwrite",jc:!0},function(e){return Q4(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",T4(e,f,"transfer").then(function(){j5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,pj:f});return g.pr.resolve(null)})):
g.pr.resolve(null)})}),0)})};
g.h.pz=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){if(1==p.j)return b.P.mf()?g.A(p,e5(),2):p.return(R0a());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.A(p,c5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];k=g.r(e);for(l=k.next();!l.done;l=k.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.hC(m.key).entityId,f.push(n));return f.length?p.return($5(b,f,b.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.h.deleteAll=function(){return $5(this,["!*$_ALL_ENTITIES_!*$"],this.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.w(b6,C5);b6.prototype.u=function(a){return u5(a)?X0a(this,a):v5(a)?Y0a(this,a):w5(a)?Z0a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var d1a=[10];g.w(e6,C5);e6.prototype.u=function(a){return u5(a)?g1a(this,a):v5(a)?h1a(this,a):w5(a)?i1a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var k1a=[10];g.w(f6,C5);f6.prototype.u=function(a){return v5(a)?m1a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(g6,C5);g6.prototype.u=function(a){return u5(a)?p1a(this,a):v5(a)?q1a(this,a):w5(a)?r1a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var t1a=[10];g.w(h6,Z5);h6.prototype.Lx=function(a){var b=Z5.prototype.Lx.call(this,a);b.ytMainDownloadedVideoEntity=new g6(a,this.environmentData,this.u);b.mainVideoEntity=new e6(a,this.u);b.mainPlaylistEntity=new b6(a,this.u);b.mainDownloadsListEntity=new f6(a,this.environmentData);return b};
h6.prototype.dJ=function(){var a=this;return g.B(function(b){return 1==b.j?g.A(b,Z5.prototype.dJ.call(a),2):a.environmentData.K("woffle_entity_migration")?g.A(b,u1a(),0):b.Oa(0)})};g.w(i6,C5);i6.prototype.u=function(a){return u5(a)?x1a(this,a):v5(a)?y1a(this,a):w5(a)?z1a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var B1a=[10];g.w(j6,Z5);j6.prototype.Lx=function(a){var b=Z5.prototype.Lx.call(this,a);b.musicTrack=new i6(a,this.u);return b};g.w(k6,g.EI);g.h=k6.prototype;g.h.create=function(){var a=this.player.R();g.cB(a)?this.j=new h6(a,this.player):g.NA(a)&&(this.j=new j6(a,this.player))};
g.h.jj=function(){return!1};
g.h.OI=function(a,b,c,d){var e=this;return g.B(function(f){return e.j?f.return($5(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.h.deleteAll=function(){return this.j.deleteAll()};
g.h.pz=function(a){return this.j.pz(a)};
g.h.BI=function(a){this.j.BI(a)};
g.h.sz=function(a){return this.j.sz(a)};
g.h.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.DI("offline",k6);})(_yt_player);
